#Requires -RunAsAdministrator
<#
.SYNOPSIS
    Install VisionSequence as a Windows service-like scheduled task that starts at boot.

.DESCRIPTION
    Registers a scheduled task that runs `manage.py serve` as the chosen account, starts it at boot
    (no login required), restarts it if it stops, and writes rotating logs under data\logs.

    A scheduled task is used rather than a real service because it needs no extra software (NSSM and
    friends), survives Windows updates, and can be inspected by anyone with Task Scheduler. The API
    process must stay single (engine state lives in it), so the task never runs more than one copy.

.EXAMPLE
    .\scripts\install_service.ps1
    .\scripts\install_service.ps1 -User "PLANT\\vision" -Port 8000
    .\scripts\install_service.ps1 -Uninstall
#>
[CmdletBinding()]
param(
    [string]$TaskName = "VisionSequence",
    [string]$User = "SYSTEM",
    [string]$Password = "",
    [int]$Port = 8000,
    [string]$BindHost = "0.0.0.0",
    [switch]$Uninstall
)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$python = Join-Path $root ".venv\Scripts\python.exe"
$runner = Join-Path $root "scripts\run_service.ps1"
$logDir = Join-Path $root "data\logs"

if ($Uninstall) {
    if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {
        Stop-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
        Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
        Write-Host "Removed scheduled task '$TaskName'." -ForegroundColor Green
    } else {
        Write-Host "No scheduled task named '$TaskName'." -ForegroundColor Yellow
    }
    return
}

if (-not (Test-Path $python)) {
    throw "No virtual environment at $python. Run .\scripts\dev.ps1 -Setup first."
}
New-Item -ItemType Directory -Force -Path $logDir | Out-Null

# The wrapper keeps the log tidy and makes the command visible in Task Scheduler.
$wrapper = @"
# Generated by install_service.ps1 — starts the API process and rotates its log.
`$ErrorActionPreference = 'Continue'
`$root = '$root'
`$log = Join-Path `$root 'data\logs\service.log'
if ((Test-Path `$log) -and ((Get-Item `$log).Length -gt 20MB)) {
    Move-Item `$log (Join-Path `$root ('data\logs\service-' + (Get-Date -Format 'yyyyMMdd-HHmmss') + '.log')) -Force
    Get-ChildItem (Join-Path `$root 'data\logs') -Filter 'service-*.log' |
        Sort-Object LastWriteTime -Descending | Select-Object -Skip 10 | Remove-Item -Force
}
Set-Location `$root
& '$python' manage.py serve --host $BindHost --port $Port *>> `$log
"@
Set-Content -Path $runner -Value $wrapper -Encoding utf8

$action = New-ScheduledTaskAction -Execute "powershell.exe" `
    -Argument "-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$runner`"" -WorkingDirectory $root
$trigger = New-ScheduledTaskTrigger -AtStartup
$settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
    -StartWhenAvailable -RestartCount 999 -RestartInterval (New-TimeSpan -Minutes 1) `
    -ExecutionTimeLimit ([TimeSpan]::Zero) -MultipleInstances IgnoreNew

if ($User -eq "SYSTEM") {
    $principal = New-ScheduledTaskPrincipal -UserId "SYSTEM" -LogonType ServiceAccount -RunLevel Highest
    Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger -Settings $settings `
        -Principal $principal -Description "VisionSequence machine vision platform" -Force | Out-Null
} else {
    if (-not $Password) { throw "A password is required when -User is not SYSTEM." }
    Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger -Settings $settings `
        -User $User -Password $Password -RunLevel Highest `
        -Description "VisionSequence machine vision platform" -Force | Out-Null
}

Start-ScheduledTask -TaskName $TaskName
Start-Sleep -Seconds 5
$state = (Get-ScheduledTask -TaskName $TaskName).State
Write-Host "Scheduled task '$TaskName' registered and started (state: $state)." -ForegroundColor Green
Write-Host "  Log:    $logDir\service.log"
Write-Host "  Health: http://127.0.0.1:$Port/healthz"
Write-Host "  Check:  .venv\Scripts\python.exe manage.py doctor"
Write-Host "Remove it with: .\scripts\install_service.ps1 -Uninstall" -ForegroundColor DarkGray
