<#
.SYNOPSIS
    HTTPS front door for the VisionSequence web interface (Caddy reverse proxy).

.DESCRIPTION
    proxy.ps1 configure -Https internal|custom|none [-HostNames a,b,10.0.0.5] [-Port 443] [-Cert x.pem -Key y.pem]
        Writes <VS_HOME>\Caddyfile. internal = Caddy's own CA (self-signed; export the root with export-root and import it
        on every client PC); custom = your certificate; none = removes the Caddyfile (plain HTTP on the API port).
    proxy.ps1 install|uninstall|start|stop|restart|status     Service "VisionSequenceProxy" (via service.ps1 -Component proxy)
    proxy.ps1 export-root [-Out certs\root.crt]               Copies the internal CA root certificate for client PCs
    proxy.ps1 trust [-File certs\root.crt]                     Imports that root into this PC's trusted roots (run on a client PC, elevated)

    The proxy listens on -Port (443) and forwards to the API on 127.0.0.1:<VISION_HTTP_PORT>; SSE is not buffered
    (flush_interval -1) and uploads up to 256 MB pass through. The web interface can only be mounted at "/" —
    distinguish stations by host name or port, never by a path prefix.
#>
[CmdletBinding()]
param(
    [Parameter(Position = 0)][ValidateSet('configure', 'install', 'uninstall', 'start', 'stop', 'restart', 'status', 'export-root', 'trust')][string]$Action = 'status',
    [ValidateSet('internal', 'custom', 'none')][string]$Https = 'internal',
    [string[]]$HostNames = @(),
    [int]$Port = 443,
    [int]$Upstream = 0,
    [string]$Cert = '',
    [string]$Key = '',
    [string]$Out = '',
    [string]$File = '',
    [switch]$DryRun
)

$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot 'vslib.ps1')
$layout = Get-VsLayout
$caddyfile = Join-Path $layout.Home 'Caddyfile'
$certsDir = Join-Path $layout.Home 'certs'
$caddyData = Join-Path $layout.DataDir 'caddy'
$rootCrt = Join-Path $caddyData 'caddy\pki\authorities\local\root.crt'
if ($Upstream -le 0) { $Upstream = [int](Get-VsSetting $layout 'VISION_HTTP_PORT' '8000') }

function Get-DefaultHostNames {
    # 主機名、localhost 與這台機器所有 IPv4（不含 APIPA）：客戶端用哪一個網址都拿得到正確的憑證。
    $names = @($env:COMPUTERNAME.ToLower(), 'localhost', '127.0.0.1')
    try {
        $fqdn = [Net.Dns]::GetHostEntry($env:COMPUTERNAME).HostName.ToLower()
        if ($fqdn -and $names -notcontains $fqdn) { $names += $fqdn }
    } catch { }
    try {
        Get-NetIPAddress -AddressFamily IPv4 -ErrorAction Stop | Where-Object { $_.IPAddress -notlike '169.254.*' -and $_.IPAddress -ne '127.0.0.1' } |
            ForEach-Object { if ($names -notcontains $_.IPAddress) { $names += $_.IPAddress } }
    } catch { }
    return $names
}

function Write-Caddyfile {
    if ($Https -eq 'none') {
        if (Test-Path -LiteralPath $caddyfile) { Remove-Item -LiteralPath $caddyfile -Force }
        Write-VsOk "HTTPS off: no Caddyfile. The API serves plain HTTP on port $Upstream (set BEHIND_HTTPS_PROXY=0 and bind 0.0.0.0)."
        return
    }
    $names = @($HostNames | Where-Object { $_ } | ForEach-Object { $_.Trim() })
    if ($names.Count -eq 0) { $names = Get-DefaultHostNames }
    $addresses = $names | ForEach-Object { if ($Port -eq 443) { $_ } else { "${_}:$Port" } }
    if ($Https -eq 'custom') {
        if (-not $Cert -or -not $Key) { throw "-Https custom needs -Cert <fullchain.pem> and -Key <private.key>." }
        foreach ($p in @($Cert, $Key)) { if (-not (Test-Path -LiteralPath $p)) { throw "File not found: $p" } }
        New-Item -ItemType Directory -Force -Path $certsDir | Out-Null
        $certDst = Join-Path $certsDir 'server.crt'
        $keyDst = Join-Path $certsDir 'server.key'
        Copy-Item -LiteralPath $Cert -Destination $certDst -Force
        Copy-Item -LiteralPath $Key -Destination $keyDst -Force
        $tls = "tls `"$certDst`" `"$keyDst`""
    } else {
        $tls = 'tls internal'
    }
    $lines = @(
        '# Generated by scripts\proxy.ps1 - VisionSequence HTTPS front door (Caddy 2).',
        "# Regenerate: vsctl proxy configure -Https $Https -HostNames <names>   |   apply edits: vsctl proxy restart",
        '{',
        '    admin off',
        '}',
        '',
        (($addresses -join ', ') + ' {'),
        "    $tls",
        '    request_body {',
        '        max_size 256MB',
        '    }',
        "    reverse_proxy 127.0.0.1:$Upstream {",
        '        flush_interval -1',
        '    }',
        '}',
        ''
    )
    $text = $lines -join "`n"
    if ($DryRun) { Write-Host $text -ForegroundColor DarkGray; return }
    [IO.File]::WriteAllText($caddyfile, $text, (New-Object Text.UTF8Encoding $false))
    Write-VsOk "Wrote $caddyfile ($Https, port $Port -> 127.0.0.1:$Upstream) for: $($names -join ', ')"
    if ($Https -eq 'internal') { Write-Host "  Client PCs must trust the CA root: vsctl proxy export-root, then import certs\root.crt (see docs/deployment.html#https)." }
}

function Export-Root {
    if (-not $Out) { $Out = Join-Path $certsDir 'root.crt' }
    for ($i = 0; $i -lt 30 -and -not (Test-Path -LiteralPath $rootCrt); $i++) { Start-Sleep -Seconds 1 }
    if (-not (Test-Path -LiteralPath $rootCrt)) { throw "Root certificate not found at $rootCrt. Is the proxy service running with -Https internal?" }
    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $Out) | Out-Null
    Copy-Item -LiteralPath $rootCrt -Destination $Out -Force
    Write-VsOk "Root certificate exported to $Out"
    Write-Host "  On each client PC (elevated): certutil -addstore -f Root root.crt   (or double-click > Install > Local Machine > Trusted Root Certification Authorities)"
}

function Import-RootHere {
    if (-not $File) { $File = Join-Path $certsDir 'root.crt' }
    if (-not (Test-Path -LiteralPath $File)) { throw "Certificate file not found: $File" }
    if (-not (Test-VsAdmin)) { throw "Run this from an elevated PowerShell (the certificate goes into the machine store)." }
    & certutil -addstore -f Root $File | Out-Null
    if ($LASTEXITCODE -ne 0) { throw "certutil failed (exit $LASTEXITCODE)" }
    Write-VsOk "Imported $File into Trusted Root Certification Authorities (Local Machine). Restart the browser."
}

$serviceScript = Join-Path $PSScriptRoot 'service.ps1'
switch ($Action) {
    'configure' { Write-Caddyfile }
    'export-root' { Export-Root }
    'trust' { Import-RootHere }
    'status' {
        $svc = Get-Service -Name 'VisionSequenceProxy' -ErrorAction SilentlyContinue
        if ($svc) { Write-Host "service VisionSequenceProxy: $($svc.Status)" } else { Write-Host "service VisionSequenceProxy: not installed" }
        if (Test-Path -LiteralPath $caddyfile) { Write-Host "Caddyfile: $caddyfile"; Get-Content -LiteralPath $caddyfile | Where-Object { $_ -match '^\S' -and $_ -notmatch '^[#{}]' } | ForEach-Object { Write-Host "  $_" } } else { Write-Host "Caddyfile: none (HTTPS off)" }
        $h = Get-VsHealth $Port 'https'
        if ($h) { Write-Host "https://127.0.0.1:$Port/healthz -> $($h.status) $($h.version)" -ForegroundColor Green } else { Write-Host "https://127.0.0.1:$Port/healthz -> not responding" -ForegroundColor Yellow }
        if (Test-Path -LiteralPath (Join-Path $certsDir 'root.crt')) { Write-Host "CA root for client PCs: $(Join-Path $certsDir 'root.crt')" }
    }
    default {
        $extra = @()
        if ($DryRun) { $extra += '-DryRun' }
        & $serviceScript $Action -Component proxy @extra
        if ($Action -eq 'install' -and -not $DryRun -and (Test-Path -LiteralPath $caddyfile) -and ((Get-Content -LiteralPath $caddyfile -Raw) -match 'tls internal')) { Export-Root }
    }
}
