# Generated by Django 5.1.6 on 2026-08-28 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0003_flowtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, default='')),
                ('param_overrides', models.JSONField(default=dict)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='flow',
            name='commissioned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flowrun',
            name='recipe',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='flowrun',
            name='station_id',
            field=models.CharField(default='ST01', max_length=40),
        ),
        migrations.AddIndex(
            model_name='flowrun',
            index=models.Index(fields=['station_id', '-started_at'], name='vision_flow_station_8fc017_idx'),
        ),
        migrations.AddField(
            model_name='flowrecipe',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='vision.flow'),
        ),
        migrations.AlterUniqueTogether(
            name='flowrecipe',
            unique_together={('flow', 'name')},
        ),
    ]
