# Generated by Django 5.1.6 on 2026-09-01 04:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0005_write_modbus_rename'),
    ]

    operations = [
        migrations.CreateModel(
            name='DlProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('trainer_kind', models.CharField(max_length=40)),
                ('classes', models.JSONField(default=list)),
                ('params', models.JSONField(default=dict)),
                ('last_asset_id', models.CharField(blank=True, default='', max_length=40)),
                ('last_metrics', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DlSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('providers', models.JSONField(default=list)),
                ('train_device', models.CharField(default='cpu', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DlSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, default='', max_length=80)),
                ('labeled_by', models.CharField(blank=True, default='', max_length=10)),
                ('score', models.FloatField(default=0)),
                ('path', models.CharField(max_length=500)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='vision.dlproject')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['project', 'label'], name='vision_dlsa_project_f90c1d_idx')],
            },
        ),
    ]
