# Generated by Django 5.1.6 on 2026-09-01 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0006_dl_teach'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlsample',
            name='shapes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
