# Generated by Django 5.1.6 on 2026-09-01 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0007_dl_shapes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DlDatasetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('note', models.TextField(blank=True, default='')),
                ('stats', models.JSONField(default=dict)),
                ('asset_id', models.CharField(blank=True, default='', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dlsample',
            name='sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='dlsample',
            name='split',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddIndex(
            model_name='dlsample',
            index=models.Index(fields=['project', 'sha256'], name='vision_dlsa_project_a730b9_idx'),
        ),
        migrations.AddField(
            model_name='dldatasetversion',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='vision.dlproject'),
        ),
    ]
