# Generated by Django 5.1.6 on 2026-09-02 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0008_dldatasetversion_dlsample_sha256_dlsample_split_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='group',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='imagesource',
            name='group',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
