# Generated by Django 5.1.6 on 2026-09-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0009_asset_group_imagesource_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('kind', 'name')},
            },
        ),
    ]
