# Generated by Django 5.1.6 on 2026-09-03 01:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0010_resourcegroup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(default='generate', max_length=20)),
                ('prompt', models.TextField(blank=True, default='')),
                ('intent', models.CharField(blank=True, default='', max_length=40)),
                ('provider', models.CharField(blank=True, default='', max_length=40)),
                ('mode', models.CharField(default='single', max_length=20)),
                ('turns', models.PositiveIntegerField(default=0)),
                ('images', models.JSONField(blank=True, default=list)),
                ('regions', models.JSONField(blank=True, default=list)),
                ('answers', models.JSONField(blank=True, default=list)),
                ('labels', models.JSONField(blank=True, default=list)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('graph', models.JSONField(default=dict)),
                ('rationale', models.TextField(blank=True, default='')),
                ('candidates', models.JSONField(blank=True, default=list)),
                ('statuses', models.JSONField(blank=True, default=list)),
                ('success', models.BooleanField(blank=True, null=True)),
                ('rating', models.SmallIntegerField(default=0)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_sessions', to='vision.flow')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=60)),
                ('scope', models.CharField(default='user', max_length=10)),
                ('markdown', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['key', 'scope'],
                'unique_together': {('key', 'scope', 'owner')},
            },
        ),
    ]
