# Generated by Django 5.1.6 on 2026-09-03 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0011_agentsession_agentskill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('source', models.CharField(blank=True, default='', max_length=120)),
                ('images', models.JSONField(blank=True, default=list)),
                ('image_count', models.PositiveIntegerField(default=0)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_sets', to='vision.flow')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_sets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_version', models.PositiveIntegerField(default=0)),
                ('graph', models.JSONField(default=dict)),
                ('recipe_name', models.CharField(blank=True, default='', max_length=80)),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('note', models.TextField(blank=True, default='')),
                ('origin', models.CharField(default='manual', max_length=12)),
                ('status', models.CharField(default='queued', max_length=12)),
                ('progress_done', models.PositiveIntegerField(default=0)),
                ('progress_total', models.PositiveIntegerField(default=0)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('items', models.JSONField(blank=True, default=list)),
                ('insights', models.JSONField(blank=True, default=dict)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_runs', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='vision.batchrun')),
                ('batch_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='vision.batchset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='batchset',
            index=models.Index(fields=['flow', '-created_at'], name='vision_batc_flow_id_ca3238_idx'),
        ),
        migrations.AddIndex(
            model_name='batchrun',
            index=models.Index(fields=['batch_set', '-created_at'], name='vision_batc_batch_s_84a4bd_idx'),
        ),
    ]
