# Generated by Django 5.1.6 on 2026-09-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0014_scriptapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='archive_policy',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='flowrun',
            name='images',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
