# Generated by Django 5.1.6 on 2026-09-04 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0016_flow_versions'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowRunHourly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.DateTimeField(db_index=True)),
                ('station_id', models.CharField(default='ST01', max_length=40)),
                ('recipe', models.CharField(blank=True, default='', max_length=80)),
                ('ok', models.PositiveIntegerField(default=0)),
                ('ng', models.PositiveIntegerField(default=0)),
                ('failed', models.PositiveIntegerField(default=0)),
                ('total_ms', models.FloatField(default=0.0)),
                ('max_ms', models.FloatField(default=0.0)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly', to='vision.flow')),
            ],
            options={
                'ordering': ['-hour'],
                'indexes': [models.Index(fields=['flow', '-hour'], name='vision_flow_flow_id_1b154d_idx')],
                'unique_together': {('flow', 'hour', 'station_id', 'recipe')},
            },
        ),
    ]
