# Generated by Django 5.1.6 on 2026-09-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0017_run_hourly'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('base_url', models.CharField(max_length=200)),
                ('api_key', models.CharField(blank=True, default='', max_length=200)),
                ('is_enabled', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
