# Generated by Django 5.1.6 on 2026-09-04 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0018_station'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Station',
        ),
    ]
