# Generated by Django 5.1.6 on 2026-09-06 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0020_assistant_memory'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('value', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='vision.flow')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('flow', 'name'), name='uniq_flow_variable')],
            },
        ),
    ]
