# Generated by Django 5.1.6 on 2026-09-06 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0021_flow_variables'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='board',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
