# Generated by Django 5.1.6 on 2026-09-06 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0022_flow_board'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.UUIDField()),
                ('name', models.CharField(max_length=80)),
                ('value', models.FloatField()),
                ('ts', models.DateTimeField()),
                ('station_id', models.CharField(default='ST01', max_length=40)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='vision.flow')),
            ],
            options={
                'indexes': [models.Index(fields=['flow', 'name', 'ts'], name='vision_meas_flow_name_ts')],
            },
        ),
    ]
