# Generated by Django 5.1.6 on 2026-09-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0024_rename_ai_tools'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetentionSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('run_days', models.PositiveIntegerField(default=365)),
                ('audit_days', models.PositiveIntegerField(default=365)),
                ('measurement_days', models.PositiveIntegerField(default=365)),
                ('archive_days', models.PositiveIntegerField(default=90)),
                ('archive_max_gb', models.FloatField(default=20.0)),
                ('backup_keep', models.PositiveIntegerField(default=10)),
                ('window_hour', models.PositiveSmallIntegerField(default=3)),
                ('vacuum', models.BooleanField(default=True)),
                ('enabled', models.BooleanField(default=True)),
                ('last_sweep_at', models.DateTimeField(blank=True, null=True)),
                ('last_deep_at', models.DateTimeField(blank=True, null=True)),
                ('last_result', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
