# Generated by Django 5.1.6 on 2026-09-06 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0026_assistant_chat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assistantchat',
            options={'ordering': ['-updated_at', '-id']},
        ),
    ]
