# Generated by Django 5.1.6 on 2026-09-08 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0027_assistant_chat_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='comm',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
