# Generated by Codex on 2026-09-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vision", "0030_flow_limits"),
    ]

    operations = [
        migrations.AddField(
            model_name="retentionsettings",
            name="file_output_days",
            field=models.PositiveIntegerField(default=90),
        ),
        migrations.AddField(
            model_name="retentionsettings",
            name="file_output_max_gb",
            field=models.FloatField(default=20.0),
        ),
    ]
