# Generated by Django 5.1.6 on 2026-09-11 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vision', '0039_node_interface'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='kind',
            field=models.CharField(choices=[('flow', 'flow'), ('tool', 'tool')], db_index=True, default='flow', max_length=8),
        ),
        migrations.CreateModel(
            name='CompositeTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(default='logic', max_length=32)),
                ('icon', models.CharField(default='Boxes', max_length=64)),
                ('builtin', models.BooleanField(default=False)),
                ('interface', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='composite_tools', to=settings.AUTH_USER_MODEL)),
                ('flow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='composite_tool', to='vision.flow')),
            ],
        ),
    ]
