# Generated by Django 5.1.6 on 2026-08-28 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vision', '0004_plan_v02_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldenBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_version', models.PositiveIntegerField()),
                ('results', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='golden_baselines', to='vision.flow')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GoldenCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image_path', models.CharField(max_length=500)),
                ('expect_status', models.CharField(default='any', max_length=8)),
                ('expect_outputs', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='golden_cases', to='vision.flow')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
