import fs from 'node:fs'; import path from 'node:path'; import { fileURLToPath } from 'node:url'; import { chromium } from 'playwright'
const here = path.dirname(fileURLToPath(import.meta.url)); const token = fs.readFileSync(path.join(here, 'token.txt'), 'utf8').trim()
const b = await chromium.launch(process.env.PW_EXE ? { executablePath: process.env.PW_EXE, headless: true } : { channel: 'chrome', headless: true })
const c = await b.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true })
await c.addInitScript(({ t }) => localStorage.setItem('vs.token', t), { t: token })
const p = await c.newPage()
await p.goto('http://127.0.0.1:5173/users', { waitUntil: 'domcontentloaded' }); await p.waitForSelector('[data-testid="role-permissions"] input[type=checkbox]', { timeout: 15000 }); await p.waitForTimeout(800)
let r = await p.evaluate(() => ({ sw: document.documentElement.scrollWidth, cw: document.documentElement.clientWidth, cb: Math.round(document.querySelector('[data-testid="role-permissions"] input[type=checkbox]').getBoundingClientRect().height) }))
console.log('USERS@390', JSON.stringify(r), r.sw <= r.cw + 1 ? '✓ 不再溢出' : '✗ 仍溢出', r.cb >= 20 ? '✓ 觸控勾選框 20px' : '✗ 勾選框仍小')
await p.goto('http://127.0.0.1:5173/settings', { waitUntil: 'domcontentloaded' }); await p.waitForTimeout(2000)
r = await p.evaluate(() => ({ sw: document.documentElement.scrollWidth, cw: document.documentElement.clientWidth, cbs: [...document.querySelectorAll('input[type=checkbox]')].map((e) => Math.round(e.getBoundingClientRect().height)) }))
console.log('SETTINGS@390', JSON.stringify(r), r.cbs.every((h) => h >= 20) ? '✓ 全部 ≥ 20px' : '✗')
await b.close()
