# Generated by Django 5.1.6 on 2026-08-21 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('devices', '0007_device_last_charge_at_device_last_discharge_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='sites',
            field=models.ManyToManyField(blank=True, help_text='Empty means every site in the organization.', related_name='scoped_memberships', to='devices.site'),
        ),
    ]
