# Generated by Django 5.1.6 on 2026-08-21 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_membership_sites'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100)),
                ('value', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ui_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_user_preference',
                'ordering': ['key'],
                'indexes': [models.Index(fields=['user', 'key'], name='accounts_us_user_id_d3e1bd_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'key'), name='uniq_user_preference_key')],
            },
        ),
    ]
