# Generated by Django 5.1.6 on 2026-08-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='reporting_currency',
            field=models.CharField(default='TWD', help_text='ISO 4217. Every tariff in this organization must match it.', max_length=8),
        ),
    ]
