/** 模組 flowio：匯出／匯入、配方（編輯器／整合頁／統計／總覽）、write_plc 工具頁與執行、warnings 提示、未教導標籤、en／深色（IO）。 */
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'

import { BASE, I18N_RE } from './full-lib.mjs'

export async function run(h) {
  await h.loginAdmin()
  await h.api.del('/vision/lock')
  const context = await h.newContext({ token: h.token })
  const page = await h.newPage(context, '[flowio]')
  const demo = h.demoFlow()
  const TMP = fs.mkdtempSync(path.join(os.tmpdir(), 'vs-full-'))
  const recent = async (id) => (await h.api.get(`/vision/flows/${id}/recent?limit=1`)).items[0]
  const resultsTab = async (p) => {
    await p.getByRole('tab', { name: /結果/ }).click().catch(async () => p.getByRole('button', { name: /結果/ }).first().click())
    await p.waitForTimeout(400)
  }
  const openEditor = async (id, p = page) => {
    await p.goto(`${BASE}/flows/${id}`)
    await p.locator('.react-flow__node').first().waitFor({ timeout: 15000 })
    await p.waitForTimeout(600)
  }
  // 示範流程上不留配方；本模組自己建 partA（結束時 full.mjs 清）
  for (const r of (await h.api.get(`/vision/flows/${demo.id}/recipes`)).items) await h.api.del(`/vision/flows/${demo.id}/recipes/${r.id}`)
  for (const c of (await h.api.get('/vision/connections')).items) if (/^E2E /.test(c.name)) await h.api.del(`/vision/connections/${c.id}`)

  let exported = ''
  await h.step('IO01 匯出', async () => {
    await page.goto(`${BASE}/flows`)
    await page.getByTestId('row-export').first().waitFor({ timeout: 15000 })
    const row = page.locator('tbody tr').filter({ hasText: demo.name }).filter({ hasNotText: '副本' })
    const [download] = await Promise.all([page.waitForEvent('download', { timeout: 15000 }), row.getByTestId('row-export').click()])
    const t = await h.toast(page, /已下載「/)
    const fname = download.suggestedFilename()
    exported = path.join(TMP, 'demo.flow.json')
    await download.saveAs(exported)
    const doc = JSON.parse(fs.readFileSync(exported, 'utf8'))
    // 編輯器頂列匯出圖示
    await openEditor(demo.id)
    const [dl2] = await Promise.all([page.waitForEvent('download', { timeout: 15000 }), page.getByTestId('btn-export').click()])
    const t2 = await h.toast(page, /已下載「/)
    const fname2 = dl2.suggestedFilename()
    h.item('IO01', /\.flow\.json$/.test(fname) && Boolean(t) && doc.schema_version && doc.name === demo.name && Array.isArray(doc.graph?.nodes) && doc.graph.nodes.length === demo.graph.nodes.length && fname2 === fname && Boolean(t2), `fname=${fname} t=${t} schema=${doc.schema_version} name=${doc.name} nodes=${doc.graph?.nodes?.length} fname2=${fname2} t2=${t2}`)
  })

  await h.step('IO02 匯入（更新既有）', async () => {
    await page.goto(`${BASE}/flows`)
    await page.getByTestId('btn-import').waitFor({ timeout: 15000 })
    const versionBefore = (await h.api.get(`/vision/flows/${demo.id}`)).version
    await page.getByTestId('btn-import').click()
    const dlg = h.dialog(page)
    await dlg.waitFor()
    const title = await dlg.locator('h2').innerText()
    await page.getByTestId('import-confirm').click()
    const tNoFile = await h.toast(page, /請先選擇 \.flow\.json 檔/)
    const dash = (await dlg.innerText()).includes('—')
    await page.getByTestId('import-input').setInputFiles(exported)
    await page.waitForTimeout(200)
    const shown = (await dlg.innerText()).includes('demo.flow.json')
    const opts = await page.getByTestId('import-source').locator('option').allInnerTexts()
    await h.shot(page, 'import-modal')
    await page.getByTestId('import-confirm').click()
    const t = await h.toast(page, /已更新流程「/)
    await page.waitForURL(new RegExp(`/flows/${demo.id}$`), { timeout: 8000 })
    const versionAfter = (await h.api.get(`/vision/flows/${demo.id}`)).version
    h.item('IO02', title.includes('匯入流程') && Boolean(tNoFile) && dash && shown && opts.some((o) => o.includes('不指定')) && opts.length >= 2 && Boolean(t) && versionAfter === versionBefore + 1 && new RegExp(`/flows/${demo.id}$`).test(page.url()), `title=${title} noFile=${tNoFile} dash=${dash} shown=${shown} opts=${opts.join('/')} t=${t} version=${versionBefore}→${versionAfter} url=${page.url()}`)
  })

  await h.step('IO03 匯入（新建＋指定來源）', async () => {
    const doc = JSON.parse(fs.readFileSync(exported, 'utf8'))
    doc.name = 'E2E 匯入流程'
    const renamed = path.join(TMP, 'renamed.flow.json')
    fs.writeFileSync(renamed, JSON.stringify(doc, null, 2))
    const src = (await h.api.get('/vision/sources')).items.find((s) => s.kind === 'synthetic') ?? (await h.api.get('/vision/sources')).items[0]
    await page.goto(`${BASE}/flows`)
    await page.getByTestId('btn-import').waitFor({ timeout: 15000 })
    await page.getByTestId('btn-import').click()
    await h.dialog(page).waitFor()
    await page.getByTestId('import-input').setInputFiles(renamed)
    await page.getByTestId('import-source').selectOption(String(src.id))
    await page.getByTestId('import-confirm').click()
    const t = await h.toast(page, /已匯入流程「E2E 匯入流程」（新建）/)
    await page.waitForURL(/\/flows\/\d+$/, { timeout: 8000 })
    const list = (await h.api.get('/vision/flows')).items
    const created = list.find((f) => f.name === 'E2E 匯入流程')
    const srcNode = created?.graph.nodes.find((n) => n.type === 'image_source')
    h.item('IO03', Boolean(t) && Boolean(created) && srcNode?.params?.source_id === src.id && page.url().endsWith(`/flows/${created?.id}`), `t=${t} created=${created?.id} source_id=${srcNode?.params?.source_id}(期望 ${src.id}) url=${page.url()}`)
    if (created) await h.api.del(`/vision/flows/${created.id}`)
  })

  await h.step('IO04 整合頁 PLC 輸出', async () => {
    await page.goto(`${BASE}/integration?tab=plc`)
    await page.getByTestId('integration-plc').waitFor({ timeout: 15000 })
    const sel = await page.getByRole('tab', { name: 'PLC 輸出' }).getAttribute('aria-selected')
    const tab = page.getByTestId('integration-plc')
    const txt = await tab.innerText()
    const code = await tab.locator('pre').first().innerText()
    const lists = await tab.locator('ul').count()
    await h.shot(page, 'integration-plc', { full: true })
    await page.getByTestId('plc-go-connections').click()
    await page.waitForURL(/\/connections$/, { timeout: 5000 })
    h.item('IO04', sel === 'true' && txt.includes('write_plc') && txt.includes('judge') && txt.includes('coil:') && txt.includes('降級') && code.includes('"src"') && code.includes('"address"') && lists >= 2 && /\/connections$/.test(page.url()), `sel=${sel} lists=${lists} code=${code.slice(0, 60).replace(/\n/g, ' ')} url=${page.url()}`)
  })

  let recipeA = null
  await h.step('IO06a 編輯器無配方時下拉隱藏', async () => {
    await openEditor(demo.id)
    const hidden = (await page.getByTestId('editor-recipe').count()) === 0
    h.item('IO06', hidden, `無配方時 editor-recipe count=${await page.getByTestId('editor-recipe').count()}`)
    recipeA = await h.api.post(`/vision/flows/${demo.id}/recipes`, { name: 'partA', is_default: true, param_overrides: { blob: { min_area: 250 } } })
  })

  await h.step('IO05 整合頁 HTTP／TCP 配方', async () => {
    await page.goto(`${BASE}/integration?tab=http`)
    await page.getByTestId('http-recipe').waitFor({ timeout: 15000 })
    await page.getByTestId('http-flow').selectOption(String(demo.id))
    await page.getByTestId('http-recipe').fill('partA')
    await page.waitForTimeout(300)
    const httpTab = page.getByTestId('integration-http')
    const curl = await httpTab.locator('pre').first().innerText()
    await httpTab.getByRole('tab', { name: 'Python' }).click()
    const py = await httpTab.locator('pre').first().innerText()
    await httpTab.getByRole('tab', { name: 'curl' }).click()
    await page.getByTestId('http-send').click()
    await page.getByTestId('http-result').waitFor({ timeout: 30000 })
    await page.waitForTimeout(500)
    const last = await recent(demo.id)
    await h.shot(page, 'integration-http-recipe')
    await page.getByRole('tab', { name: 'TCP 測試' }).click()
    await page.waitForTimeout(500)
    const chips = await page.getByTestId('integration-tcp').locator('button.font-mono').allInnerTexts()
    const chip = chips.find((c) => /recipe=/.test(c))
    await page.getByTestId('tcp-command').fill(`RUN ${demo.id} recipe=partA`)
    await page.getByTestId('tcp-send').click()
    const tcpErr = await h.toast(page, /失敗|錯誤|error/i, 3000)
    await page.getByTestId('tcp-result').waitFor({ timeout: 60000 })
    await page.waitForTimeout(500)
    const tcpTxt = (await page.getByTestId('tcp-result').innerText()) + (tcpErr ? ` toast=${tcpErr}` : '')
    const lastTcp = await recent(demo.id)
    h.item('IO05', curl.includes('"recipe": "partA"') && py.includes('"recipe": "partA"') && last?.recipe === 'partA' && /^RUN \d+ recipe=<name>$/.test(chip ?? '') && /"recipe":\s*"partA"/.test(tcpTxt) && lastTcp?.recipe === 'partA', `curl=${curl.includes('"recipe": "partA"')} py=${py.includes('"recipe": "partA"')} http.recipe=${last?.recipe} chip=${chip} tcp.recipe=${lastTcp?.recipe} tcpTxt=${tcpTxt.replace(/\s+/g, ' ').slice(0, 160)}`)
  })

  await h.step('IO06 編輯器綁定配方下拉', async () => {
    // 改版後：編輯器頂列的下拉是「綁定」（is_default），不是每次試跑挑配方；執行一次／試跑都用綁定的配方
    await openEditor(demo.id)
    const sel = page.getByTestId('editor-recipe')
    const opts = await sel.locator('option').allInnerTexts()
    const chosen = await sel.locator('option:checked').innerText()
    const label = await sel.locator('xpath=..').innerText()
    await sel.selectOption('')
    const tNone = await h.toast(page, /已改為不用配方/)
    await page.waitForTimeout(400)
    const unbound = (await h.api.get(`/vision/flows/${demo.id}/recipes`)).items.every((r) => !r.is_default)
    await h.waitGone(page.locator('[role=status] .card'), 4000)
    await sel.selectOption(String(recipeA.id))
    const tBound = await h.toast(page, /已綁定配方「partA」/)
    await page.waitForTimeout(400)
    await page.getByTestId('btn-preview').click()
    await h.toast(page, /試跑完成/, 15000)
    // 「執行一次」按鈕已移除：整合方走 API（未指定 recipe → 綁定配方）
    await h.api.post(`/vision/flows/${demo.id}/run`, { context: null, wait: true })
    await page.waitForTimeout(800)
    const last = await recent(demo.id)
    await resultsTab(page)
    const table = await page.locator('[data-testid=inspector-pane] table').first().innerText()
    await h.shot(page, 'editor-recipe-run')
    h.item('IO06', opts.length === 2 && opts[0].includes('不用配方') && opts[1] === 'partA' && chosen === 'partA' && label.includes('綁定') && Boolean(tNone) && unbound && Boolean(tBound) && last?.recipe === 'partA' && table.includes('配方') && table.includes('partA'), `opts=${opts.join('/')} chosen=${chosen} label=${label.replace(/\n/g, ' ')} none=${tNone}/${unbound} bound=${tBound} run.recipe=${last?.recipe} table=${table.replace(/\n/g, '|').slice(0, 80)}`)
  })

  await h.step('IO08 總覽與統計的站台／配方', async () => {
    await page.goto(`${BASE}/`)
    await page.waitForLoadState('networkidle')
    await page.waitForTimeout(800)
    const card = page.locator('main a.card').filter({ hasText: demo.name })
    const meta = await card.getByTestId('card-meta').innerText().catch(() => '')
    await h.shot(page, 'dashboard-meta')
    await page.goto(`${BASE}/flows/${demo.id}/stats`)
    await page.getByTestId('stats-kpi').waitFor({ timeout: 15000 })
    await page.getByTestId('history-recipe').first().waitFor({ timeout: 15000 }).catch(() => null)
    await page.waitForTimeout(400)
    const header = await page.locator('main').locator('h1, h2').first().locator('xpath=..').innerText()
    const th = await page.locator('main thead').last().innerText()
    const cells = await page.getByTestId('history-recipe').allInnerTexts()
    const stations = await page.locator('main tbody tr td:nth-child(5)').allInnerTexts()
    await h.shot(page, 'stats-recipe')
    h.item('IO08', meta.includes('站台') && meta.includes('ST01') && meta.includes('配方') && meta.includes('partA') && header.includes('站台') && header.includes('partA') && th.includes('配方') && th.includes('站台') && cells.includes('partA') && stations.some((s) => s.includes('ST01')), `meta=${meta.replace(/\n/g, ' ')} header=${header.replace(/\n/g, ' ').slice(0, 100)} th=${th.replace(/\n/g, '|')} cells=${cells.slice(0, 3)} stations=${stations.slice(0, 2)}`)
  })

  const plcFlow = await h.cloneDemo('E2E PLC')
  await h.step('IO09 IO10 warnings 與未教導標籤', async () => {
    await h.api.patch(`/vision/flows/${plcFlow}`, { commissioned: false })
    await page.goto(`${BASE}/flows`)
    await page.getByTestId('row-export').first().waitFor({ timeout: 15000 })
    const row = page.locator('tbody tr').filter({ hasText: 'E2E PLC' })
    const badge = (await row.innerText()).includes('未教導')
    const demoRow = page.locator('tbody tr').filter({ hasText: demo.name }).filter({ hasNotText: '副本' })
    // 改版後：列名稱旁「綁定：partA」＋綁定欄「配方 (1)」鈕
    const demoTxt = await demoRow.innerText()
    const recipeCount = demoTxt.includes('綁定：partA') && /配方 \(1\)/.test(demoTxt)
    await h.shot(page, 'flows-not-commissioned')
    await page.goto(`${BASE}/`)
    await page.waitForLoadState('networkidle')
    await page.waitForTimeout(600)
    const dashBadge = (await page.locator('main a.card').filter({ hasText: 'E2E PLC' }).innerText()).includes('未教導')
    await openEditor(plcFlow)
    const tb = (await page.getByTestId('not-commissioned-badge').count()) === 1
    await h.api.post(`/vision/flows/${plcFlow}/run`, { context: null, wait: true })
    await page.waitForTimeout(800)
    await resultsTab(page)
    const warn = await page.getByTestId('run-warnings').innerText().catch(() => '')
    await h.shot(page, 'results-warnings')
    h.item('IO10', badge && recipeCount && dashBadge && tb, `list=${badge} recipeCount=${recipeCount} dash=${dashBadge} toolbar=${tb}`)
    // 走 UI：頂列標籤 → 參數卡「標記為已教導」→ 返回編輯器
    await page.getByTestId('not-commissioned-badge').click()
    await page.waitForURL(/\/teach$/, { timeout: 5000 })
    await page.getByTestId('teach-mark').waitFor({ timeout: 15000 })
    await page.getByTestId('teach-mark').click()
    await h.toast(page, /已標記為已教導/)
    await page.getByTestId('btn-back').click()
    await page.locator('.react-flow__node').first().waitFor({ timeout: 15000 })
    await page.waitForTimeout(500)
    const tbGone = (await page.getByTestId('not-commissioned-badge').count()) === 0
    await h.api.post(`/vision/flows/${plcFlow}/run`, { context: null, wait: true })
    await page.waitForTimeout(800)
    const warnGone = (await page.getByTestId('run-warnings').count()) === 0
    const last = await recent(plcFlow)
    h.item('IO09', warn.includes('未完成現場教導') && tbGone && warnGone && (last?.warnings?.length ?? 0) === 0, `warn=${warn.replace(/\n/g, ' ')} tbGone=${tbGone} warnGone=${warnGone} api=${JSON.stringify(last?.warnings)}`)
  })

  await h.step('IO07 write_plc 工具與執行', async () => {
    const conn = await h.api.post('/vision/connections', { name: 'E2E plc-sim', kind: 'dio_sim', config: { channels: ['DO0', 'OK', 'NG'] }, is_enabled: true })
    await openEditor(plcFlow)
    const palette = page.locator('aside').first()
    await palette.locator('input[placeholder^="搜尋"]').fill('PLC')
    await page.waitForTimeout(200)
    // 工具箱一律拖曳新增：直接對畫布 dispatch drop
    await page.evaluate(() => {
      const pane = document.querySelector('.react-flow__pane')
      const r = pane.getBoundingClientRect()
      const dt = new DataTransfer()
      dt.setData('application/x-vs-tool', 'write_plc')
      // 放在畫布中上方（放太右下會被小地圖蓋住點不到）
      const x = r.left + r.width * 0.55
      const y = r.top + r.height * 0.3
      pane.dispatchEvent(new DragEvent('dragover', { bubbles: true, cancelable: true, dataTransfer: dt, clientX: x, clientY: y }))
      pane.dispatchEvent(new DragEvent('drop', { bubbles: true, cancelable: true, dataTransfer: dt, clientX: x, clientY: y }))
    })
    await page.waitForTimeout(400)
    const nodeId = await page.locator('.react-flow__node.selected').getAttribute('data-id')
    await page.keyboard.press('Control+s')
    await h.toast(page, /流程已儲存/)
    await page.waitForTimeout(400)
    await page.goto(`${BASE}/flows/${plcFlow}/tools/${nodeId}`)
    await page.getByTestId('param-connection').waitFor({ timeout: 15000 })
    const listId = await page.getByTestId('param-connection').getAttribute('list')
    const opts = await page.locator(`datalist[id="${listId}"] option`).evaluateAll((els) => els.map((e) => e.value))
    const hint = await page.locator('[data-param=connection]').innerText()
    await page.getByTestId('param-connection').fill('E2E plc-sim')
    const mapping = page.locator('[data-param=mapping] textarea')
    const isTextarea = (await mapping.count()) === 1
    await mapping.fill('{bad json')
    await page.waitForTimeout(200)
    const errTxt = await page.locator('[data-param=mapping]').innerText()
    await mapping.fill('[{"src": "judge", "address": "OK", "dtype": "bool"}, {"value": 1, "address": "DO0", "dtype": "bool"}]')
    await page.waitForTimeout(300)
    const errGone = !/JSON/.test(await page.locator('[data-param=mapping] .text-critical').innerText().catch(() => ''))
    const onError = page.locator('[data-param=on_error] select')
    const onErrorOpts = await onError.locator('option').evaluateAll((els) => els.map((e) => e.value))
    await onError.selectOption('warn')
    await h.shot(page, 'tool-write-plc')
    await page.keyboard.press('Control+s')
    await h.toast(page, /已儲存/)
    await page.waitForTimeout(500)
    const saved = (await h.api.get(`/vision/flows/${plcFlow}`)).graph.nodes.find((n) => n.id === nodeId)
    h.item('N11', isTextarea && /JSON/.test(errTxt) && errGone && Array.isArray(saved?.params?.mapping) && saved.params.mapping.length === 2, `json 欄位：textarea=${isTextarea} err=${/JSON/.test(errTxt)} errGone=${errGone} saved=${JSON.stringify(saved?.params?.mapping)}`)
    await openEditor(plcFlow)
    await h.api.post(`/vision/flows/${plcFlow}/run`, { context: null, wait: true })
    await page.waitForTimeout(800)
    let run = await recent(plcFlow)
    const plc = run?.nodes?.[nodeId]
    const state = await h.api.get(`/vision/connections/${conn.id}/state`)
    // 降級：連線不存在
    const g = (await h.api.get(`/vision/flows/${plcFlow}`)).graph
    g.nodes.find((n) => n.id === nodeId).params.connection = 'no-such-conn'
    await h.api.patch(`/vision/flows/${plcFlow}`, { graph: g })
    await page.reload()
    await page.locator('.react-flow__node').first().waitFor({ timeout: 15000 })
    await page.waitForTimeout(600)
    await h.api.post(`/vision/flows/${plcFlow}/run`, { context: null, wait: true })
    await page.waitForTimeout(800)
    run = await recent(plcFlow)
    const degraded = run?.nodes?.[nodeId]
    // 改版後雙擊會開工具頁：改成點選步驟 → 結果分頁看訊息
    await page.locator(`.react-flow__node[data-id="${nodeId}"]`).click()
    await resultsTab(page)
    const panel = await page.getByTestId('inspector-pane').innerText()
    await h.shot(page, 'editor-write-plc-degraded')
    h.item('IO07', opts.includes('E2E plc-sim') && hint.includes('連線') && onErrorOpts.includes('warn') && onErrorOpts.includes('fail') && plc?.status === 'ok' && plc?.outputs?.written >= 1 && (state?.values?.DO0 === 1 || state?.values?.DO0 === true) && run?.status !== 'failed' && degraded?.outputs?.ok === false && /降級/.test(degraded?.message ?? '') && panel.includes('降級'), `opts=${opts} hint=${hint.replace(/\n/g, ' ').slice(0, 40)} onError=${onErrorOpts} plc=${plc?.status}/${JSON.stringify(plc?.outputs)} state=${JSON.stringify(state?.values)} degraded=${degraded?.status}/${degraded?.message} run=${run?.status} panel=${panel.includes('降級')}`)
    await h.api.del(`/vision/connections/${conn.id}`)
  })

  await h.step('IO11 en 模式', async () => {
    const ctx = await h.newContext({ token: h.token, locale: 'en-US' })
    await ctx.addInitScript(() => localStorage.setItem('vs.language', 'en'))
    const en = await h.newPage(ctx, '[flowio-en]')
    const raw = []
    const check = async (tag) => {
      const text = await en.evaluate(() => document.body.innerText)
      const keys = [...text.matchAll(I18N_RE)].map((m) => m[0].trim())
      if (keys.length) raw.push(`${tag}: ${[...new Set(keys)].slice(0, 5).join(',')}`)
    }
    await en.goto(`${BASE}/flows/${demo.id}/teach`)
    await en.getByTestId('teach-group').first().waitFor({ timeout: 15000 })
    await en.getByTestId('teach-updating').waitFor({ state: 'detached', timeout: 20000 }).catch(() => null)
    await en.waitForTimeout(300)
    const teachHdr = await en.locator('[data-testid=teach-page] header').innerText()
    await h.shot(en, 'en-teach')
    await check('teach')
    await en.getByTestId('teach-manage').click()
    await h.dialog(en).waitFor()
    await en.getByTestId('recipe-detail').waitFor({ timeout: 5000 }).catch(() => null)
    await h.shot(en, 'en-recipe-manager')
    await check('recipe-manager')
    await en.keyboard.press('Escape')
    await en.goto(`${BASE}/flows/${demo.id}/golden`)
    await en.getByTestId('golden-regress').waitFor({ timeout: 15000 })
    await en.waitForTimeout(400)
    const goldenTxt = await en.locator('main').innerText()
    await h.shot(en, 'en-golden')
    await check('golden')
    await en.goto(`${BASE}/connections`)
    await en.getByTestId('conn-create').waitFor({ timeout: 15000 })
    await en.waitForTimeout(400)
    await en.getByTestId('conn-create').click()
    await h.dialog(en).waitFor()
    await en.getByTestId('conn-kind').selectOption('modbus_tcp')
    await h.shot(en, 'en-connections-form')
    await check('connections-form')
    await en.keyboard.press('Escape')
    await en.goto(`${BASE}/integration?tab=plc`)
    await en.getByTestId('integration-plc').waitFor({ timeout: 15000 })
    await h.shot(en, 'en-integration-plc')
    await check('integration-plc')
    await en.goto(`${BASE}/flows`)
    await en.getByTestId('btn-import').waitFor({ timeout: 15000 })
    await en.getByTestId('btn-import').click()
    await h.dialog(en).waitFor()
    await h.shot(en, 'en-import-modal')
    await check('import-modal')
    await en.keyboard.press('Escape')
    await ctx.close()
    h.item('IO11', raw.length === 0 && teachHdr.includes('Teach page') && teachHdr.includes('Back to editor') && /Golden Set/.test(goldenTxt) && /Run regression|Regression/i.test(goldenTxt) && !/參數卡|返回編輯器|執行回歸/.test(goldenTxt + teachHdr), `raw=${raw.join(' | ')} teachHdr=${teachHdr.replace(/\n/g, ' ').slice(0, 80)} golden=${goldenTxt.replace(/\n/g, ' ').slice(0, 80)}`)
  })

  await h.step('IO12 深色截圖', async () => {
    const dark = await h.newContext({ token: h.token, colorScheme: 'dark' })
    await dark.addInitScript(() => localStorage.setItem('vs.theme', 'dark'))
    const dp = await h.newPage(dark, '[flowio-dark]')
    await dp.goto(`${BASE}/flows/${demo.id}/teach`)
    await dp.getByTestId('teach-group').first().waitFor({ timeout: 15000 })
    await dp.getByTestId('teach-updating').waitFor({ state: 'detached', timeout: 20000 }).catch(() => null)
    await dp.waitForTimeout(300)
    await h.shot(dp, 'dark-teach')
    await dp.goto(`${BASE}/flows/${demo.id}/golden`)
    await dp.getByTestId('golden-regress').waitFor({ timeout: 15000 })
    await dp.waitForTimeout(400)
    await h.shot(dp, 'dark-golden')
    await dp.goto(`${BASE}/connections`)
    await dp.getByTestId('conn-create').waitFor({ timeout: 15000 })
    await dp.waitForTimeout(400)
    await h.shot(dp, 'dark-connections')
    await dp.goto(`${BASE}/integration?tab=plc`)
    await dp.getByTestId('integration-plc').waitFor({ timeout: 15000 })
    await h.shot(dp, 'dark-integration-plc')
    const isDark = await dp.evaluate(() => document.documentElement.classList.contains('dark'))
    await dark.close()
    h.item('IO12', isDark, `dark=${isDark}`)
  })

  await context.close()
}
