/** 模組 pages：總覽（C）、流程列表（D）、範本畫廊（E 的 create 部分）、影像來源庫（P）、資產庫（Q）、說明頁（T）、設定頁（U01/U02/U06/U07）、統計頁（O）。 */
import { BASE } from './full-lib.mjs'

export async function run(h) {
  await h.loginAdmin()
  const context = await h.newContext({ token: h.token })
  const page = await h.newPage(context, '[pages]')
  const demo = h.demoFlow()

  // ============ C. 總覽 ============
  await h.step('C01-C03 總覽卡片', async () => {
    await page.goto(`${BASE}/`)
    await page.waitForLoadState('networkidle')
    await page.waitForTimeout(800)
    const live = (await page.locator('main').innerText()).includes('即時')
    h.item('C01', live, '未顯示「即時」badge')
    const cap = await page.locator('main .card').first().innerText()
    h.item('C02', /忙碌/.test(cap) && /快取 \d+ 張影像/.test(cap), `cap=${cap.replace(/\n/g, '|')}`)
    const card = page.locator('main a.card').filter({ hasText: demo.name })
    const txt = await card.innerText()
    const ok = ['最近判定', '次數', '平均', '最大', 'ms'].every((k) => txt.includes(k))
    await h.shot(page, 'dashboard')
    h.item('C03', ok && (await card.locator('.rounded-full').first().count()) === 1, `card=${txt.replace(/\n/g, '|')}`)
  })

  await h.step('C06-C07 卡片導覽', async () => {
    const card = page.locator('main a.card').filter({ hasText: demo.name })
    await card.getByTestId('card-stats').click()
    await page.waitForURL(/\/stats$/, { timeout: 5000 })
    const toStats = /\/stats$/.test(page.url())
    await page.goBack()
    await page.waitForLoadState('networkidle')
    await page.locator('main a.card').filter({ hasText: demo.name }).click()
    await page.waitForURL(new RegExp(`/flows/${demo.id}$`), { timeout: 5000 })
    h.item('C06', toStats, `url=${page.url()}`)
    h.item('C07', new RegExp(`/flows/${demo.id}$`).test(page.url()), `url=${page.url()}`)
  })

  await h.step('C10 SSE 即時更新', async () => {
    await page.goto(`${BASE}/`)
    await page.waitForLoadState('networkidle')
    await page.waitForTimeout(800)
    const card = page.locator('main a.card').filter({ hasText: demo.name })
    const before = await card.innerText()
    await h.api.post(`/vision/flows/${demo.id}/run?wait=1`, { context: null, wait: true })
    await page.waitForTimeout(1500)
    const after = await card.innerText()
    const runsBefore = Number(/次數\s+(\d+)/.exec(before)?.[1] ?? -1)
    const runsAfter = Number(/次數\s+(\d+)/.exec(after)?.[1] ?? -1)
    h.item('C10', runsAfter === runsBefore + 1, `runs ${runsBefore} → ${runsAfter}`)
  })

  await h.step('C04-C05 連續／停用 badge', async () => {
    await h.api.post(`/vision/flows/${demo.id}/continuous`, { running: true })
    await page.waitForTimeout(1500)
    const card = page.locator('main a.card').filter({ hasText: demo.name })
    const cont = (await card.innerText()).includes('連續執行中')
    await h.shot(page, 'dashboard-continuous')
    await h.api.post(`/vision/flows/${demo.id}/continuous`, { running: false })
    await page.waitForTimeout(800)
    h.item('C04', cont, '連續執行時卡片無 badge')
    await h.api.patch(`/vision/flows/${demo.id}`, { is_enabled: false })
    await page.reload()
    await page.waitForLoadState('networkidle')
    await page.waitForTimeout(500)
    const dis = (await page.locator('main a.card').filter({ hasText: demo.name }).innerText()).includes('停用')
    await h.api.patch(`/vision/flows/${demo.id}`, { is_enabled: true })
    h.item('C05', dis, '停用流程卡片無「停用」badge')
  })

  await h.step('C08-C09 空狀態／錯誤狀態', async () => {
    await page.route('**/api/vision/flows?*', (route) => route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ items: [], total: 0 }) }))
    await page.reload()
    await page.waitForLoadState('networkidle')
    await page.waitForTimeout(500)
    const txt = await page.locator('main').innerText()
    await h.shot(page, 'dashboard-empty')
    h.item('C08', txt.includes('還沒有任何流程') && (await page.getByRole('button', { name: '新增流程' }).count()) === 1, `main=${txt.slice(0, 120).replace(/\n/g, '|')}`)
    await page.unroute('**/api/vision/flows?*')
    const un = h.allowStatus(/500 GET .*\/api\/vision\/flows/)
    await page.route('**/api/vision/flows?*', (route) => route.fulfill({ status: 500, contentType: 'application/json', body: JSON.stringify({ error: { code: 'boom', message: '伺服器爆炸' } }) }))
    await page.reload()
    await page.waitForTimeout(2500)
    const err = await page.locator('main').innerText()
    await h.shot(page, 'dashboard-error')
    await page.unroute('**/api/vision/flows?*')
    await page.getByRole('button', { name: '重試' }).click()
    await page.waitForTimeout(1000)
    const recovered = (await page.locator('main a.card').count()) > 0
    un()
    h.item('C09', err.includes('伺服器爆炸') && recovered, `err=${err.slice(0, 80).replace(/\n/g, '|')} recovered=${recovered}`)
  })

  await h.step('C11 總覽深色', async () => {
    await page.evaluate(() => localStorage.setItem('vs.theme', 'dark'))
    await page.reload()
    await page.waitForLoadState('networkidle')
    await page.waitForTimeout(600)
    const dark = await page.evaluate(() => document.documentElement.classList.contains('dark'))
    await h.shot(page, 'dashboard-dark')
    h.item('C11', dark, 'localStorage vs.theme=dark 未生效')
    await page.evaluate(() => localStorage.removeItem('vs.theme'))
  })

  // ============ D. 流程列表 ============
  await h.step('D03 表格欄位', async () => {
    await page.goto(`${BASE}/flows`)
    await page.waitForLoadState('networkidle')
    await page.waitForTimeout(500)
    const head = await page.locator('thead').innerText()
    const row = page.locator('tbody tr').filter({ hasText: demo.name })
    const txt = await row.innerText()
    const icons = await row.locator('td:last-child button').count()
    await h.shot(page, 'flows')
    h.item('D03', ['名稱', '擁有者', '啟用', '步驟', '版本', '統計', '更新時間', '操作'].every((k) => head.includes(k)) && txt.includes('共用') && /v\d+/.test(txt) && /\d+ 次/.test(txt) && icons === 7, `head=${head.replace(/\n/g, '|')} row=${txt.replace(/\n/g, '|')} icons=${icons}`)
  })

  await h.step('D01 搜尋', async () => {
    const box = page.locator('input[placeholder^="搜尋"]')
    await box.fill('曝光')
    await page.waitForTimeout(800)
    const rows = await page.locator('tbody tr').count()
    const only = rows === 1 && (await page.locator('tbody').innerText()).includes('曝光')
    await box.fill('zzz-不存在')
    await page.waitForTimeout(800)
    const empty = await page.locator('tbody').innerText()
    await h.shot(page, 'flows-empty-search')
    h.item('D10', empty.includes('還沒有流程') && empty.includes('新增流程'), `empty=${empty}`)
    await box.fill('')
    await page.waitForTimeout(600)
    h.item('D01', only && (await page.locator('tbody tr').count()) >= 2, `rows(曝光)=${rows}`)
  })

  await h.step('D02 只看我的', async () => {
    await page.getByRole('switch', { name: '只看我的' }).click()
    await page.waitForTimeout(800)
    const txt = await page.locator('tbody').innerText()
    const on = await page.getByRole('switch', { name: '只看我的' }).getAttribute('aria-checked')
    await page.getByRole('switch', { name: '只看我的' }).click()
    await page.waitForTimeout(500)
    h.item('D02', on === 'true' && txt.includes('還沒有流程'), `aria-checked=${on} tbody=${txt.slice(0, 60)}`)
  })

  await h.step('D06 啟用開關', async () => {
    const row = () => page.locator('tbody tr').filter({ hasText: demo.name })
    await row().getByRole('switch').click()
    await page.waitForTimeout(800)
    const off = (await h.api.get(`/vision/flows/${demo.id}`)).is_enabled === false
    const ui = await row().getByRole('switch').getAttribute('aria-checked')
    await row().getByRole('switch').click()
    await page.waitForTimeout(800)
    const on = (await h.api.get(`/vision/flows/${demo.id}`)).is_enabled === true
    h.item('D06', off && ui === 'false' && on, `off=${off} ui=${ui} on=${on}`)
  })

  await h.step('D07 列點擊與操作區', async () => {
    const row = page.locator('tbody tr').filter({ hasText: demo.name })
    await row.getByRole('button', { name: '複製' }).click()
    const t = await h.toast(page, /已複製流程/)
    const stayed = /\/flows$/.test(page.url())
    await page.waitForTimeout(600)
    const copies = await page.locator('tbody tr').filter({ hasText: demo.name }).count()
    h.item('D08', Boolean(t) && copies >= 2, `toast=${t} copies=${copies}`)
    h.item('D07', stayed, '操作區點擊觸發了列導覽')
    await row.first().click()
    await page.waitForURL(new RegExp(`/flows/\\d+$`), { timeout: 5000 })
    h.item('D07', /\/flows\/\d+$/.test(page.url()), `url=${page.url()}`)
    await page.goto(`${BASE}/flows`)
    await page.waitForLoadState('networkidle')
  })

  await h.step('D09 刪除', async () => {
    const copy = page.locator('tbody tr').filter({ hasText: demo.name }).last()
    const name = (await copy.locator('td').first().innerText()).split('\n')[0]
    await copy.getByRole('button', { name: '刪除' }).click()
    const dlg = h.dialog(page)
    const msg = await dlg.innerText()
    const danger = (await dlg.locator('button.bg-critical').count()) === 1
    await h.shot(page, 'flows-delete-confirm')
    await dlg.getByRole('button', { name: '刪除' }).click()
    const t = await h.toast(page, /已刪除流程/)
    await page.waitForTimeout(600)
    const left = await page.locator('tbody tr').filter({ hasText: demo.name }).count()
    h.item('D09', msg.includes(name.slice(0, 6)) && danger && Boolean(t) && left === 1, `msg=${msg} danger=${danger} toast=${t} left=${left}`)
  })

  await h.step('D04-D05 新增流程 Modal', async () => {
    await page.getByRole('button', { name: '新增流程' }).click()
    const dlg = h.dialog(page)
    await dlg.getByRole('button', { name: '新增', exact: true }).click()
    const t1 = await h.toast(page, /請輸入名稱/)
    await dlg.getByLabel('名稱').fill('E2E 暫時流程')
    await page.keyboard.press('Escape')
    const asked = (await dlg.locator('[role=alertdialog]').count()) === 1
    await dlg.getByRole('button', { name: '繼續編輯' }).click()
    await page.mouse.click(20, 500)
    const asked2 = (await dlg.locator('[role=alertdialog]').count()) === 1
    await dlg.getByRole('button', { name: '繼續編輯' }).click()
    h.item('D05', asked && asked2, `esc=${asked} backdrop=${asked2}`)
    await dlg.getByLabel('名稱').press('Enter')
    const t2 = await h.toast(page, /已建立流程/)
    await page.waitForURL(/\/flows\/\d+$/, { timeout: 8000 })
    h.tmpFlowId = Number(page.url().split('/').pop())
    h.item('D04', Boolean(t1) && Boolean(t2) && /\/flows\/\d+$/.test(page.url()), `t1=${t1} t2=${t2} url=${page.url()}`)
    // H05 新流程步驟清單空狀態
    await page.waitForTimeout(800)
    const left = await page.locator('aside').first().innerText()
    h.item('H05', left.includes('畫布上還沒有步驟'), `left=${left.slice(-60)}`)
  })

  await h.step('D12 長名稱', async () => {
    const long = 'E2E 非常長的流程名稱'.padEnd(120, '名稱很長很長') + ' 結尾'
    const f = await h.api.post('/vision/flows', { name: long, description: 'x'.repeat(300) })
    await page.goto(`${BASE}/flows`)
    await page.waitForLoadState('networkidle')
    await page.waitForTimeout(500)
    await h.shot(page, 'flows-long-name')
    const noScroll = await page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth + 1)
    const rowH = await page.locator('tbody tr').filter({ hasText: 'E2E 非常長' }).boundingBox()
    await h.api.del(`/vision/flows/${f.id}`)
    h.item('D12', noScroll && rowH && rowH.height < 200, `noScroll=${noScroll} rowHeight=${rowH?.height}`)
  })

  await h.step('D13 錯誤狀態', async () => {
    const un = h.allowStatus(/500 GET .*\/api\/vision\/flows/)
    await page.route('**/api/vision/flows?*', (route) => route.fulfill({ status: 500, contentType: 'application/json', body: JSON.stringify({ error: { code: 'boom', message: '列表壞掉' } }) }))
    await page.reload()
    await page.waitForTimeout(2500)
    const err = await page.locator('main').innerText()
    await page.unroute('**/api/vision/flows?*')
    await page.getByRole('button', { name: '重試' }).click()
    await page.waitForTimeout(1000)
    const rows = await page.locator('tbody tr').count()
    un()
    h.item('D13', err.includes('列表壞掉') && rows >= 2, `err=${err.slice(0, 60).replace(/\n/g, '|')} rows=${rows}`)
  })

  // ============ E. 範本畫廊（create 模式） ============
  await h.step('E01-E06 範本畫廊建立', async () => {
    await page.getByTestId('btn-from-template').click()
    const dlg = h.dialog(page)
    await page.getByTestId('template-card').first().waitFor({ timeout: 10000 })
    await page.waitForTimeout(400)
    h.item('D11', (await dlg.locator('h2').innerText()).includes('範本畫廊'), '從範本建立未開啟範本畫廊')
    const cards = await page.getByTestId('template-card').count()
    const first = await page.getByTestId('template-card').first().innerText()
    const svg = await page.getByTestId('template-card').first().locator('svg rect').count()
    await h.shot(page, 'template-gallery')
    h.item('E01', cards >= 5 && svg > 0 && first.includes('內建') && /\d+ 個步驟/.test(first), `cards=${cards} svg=${svg} first=${first.replace(/\n/g, '|')}`)
    const search = dlg.locator('input[placeholder^="搜尋"]')
    await search.fill('孔')
    await page.waitForTimeout(300)
    const n1 = await page.getByTestId('template-card').count()
    await search.fill('zzz')
    await page.waitForTimeout(300)
    const emptyTxt = await page.getByTestId('template-grid').innerText()
    await search.fill('')
    h.item('E02', n1 >= 1 && n1 < cards && emptyTxt.includes('沒有符合的範本'), `n1=${n1} empty=${emptyTxt}`)
    const confirmBtn = page.getByTestId('template-confirm')
    const disabledBefore = await confirmBtn.isDisabled()
    await page.locator('[data-template-id="builtin:hole_count"]').click()
    const nameVal = await page.getByTestId('template-flow-name').inputValue()
    const side = await dlg.locator('.space-y-3').last().innerText()
    h.item('E03', nameVal.length > 0 && side.includes(nameVal), `name=${nameVal} side=${side.slice(0, 60).replace(/\n/g, '|')}`)
    const opts = await page.getByTestId('template-source').locator('option').allInnerTexts()
    h.item('E04', opts.length >= 2 && opts[0].includes('先不選'), `opts=${opts.join('|')}`)
    await page.getByTestId('template-flow-name').fill('')
    await confirmBtn.click()
    const t1 = await h.toast(page, /請輸入名稱/)
    h.item('E05', disabledBefore && Boolean(t1), `disabledBefore=${disabledBefore} toast=${t1}`)
    await page.getByTestId('template-flow-name').fill('E2E 範本流程（無來源）')
    await confirmBtn.click()
    const t2 = await h.toast(page, /請在取像步驟選擇影像來源/)
    await page.waitForURL(/\/flows\/\d+$/, { timeout: 10000 })
    h.tmpFlowFromTemplate = Number(page.url().split('/').pop())
    await page.locator('.react-flow__node').first().waitFor({ timeout: 15000 })
    await page.waitForTimeout(800)
    // source_id 是選填（可改用暫存／API 送圖），所以只以 warning toast 提醒，頂列不算問題。
    const created = await h.api.get(`/vision/flows/${h.tmpFlowFromTemplate}`)
    const srcParam = created.graph.nodes.find((n) => n.type === 'image_source')?.params?.source_id
    await h.shot(page, 'flow-from-template-missing-source')
    h.item('E06', Boolean(t2) && (srcParam === null || srcParam === undefined || srcParam === ''), `toast=${t2} source_id=${JSON.stringify(srcParam)}`)
  })

  await h.step('E10 Esc 關閉畫廊', async () => {
    await page.goto(`${BASE}/flows`)
    await page.waitForLoadState('networkidle')
    await page.getByTestId('btn-from-template').click()
    await h.dialog(page).waitFor()
    await page.keyboard.press('Escape')
    const gone = await h.waitGone(page.locator('[role=dialog]'))
    h.item('E10', gone, 'Esc 未關閉畫廊')
  })

  // ============ P. 影像來源庫 ============
  await h.step('P01 表格', async () => {
    await page.goto(`${BASE}/sources`)
    await page.waitForLoadState('networkidle')
    await page.waitForTimeout(500)
    const head = await page.locator('thead').innerText()
    const row = page.locator('tbody tr').first()
    const txt = await row.innerText()
    const title = await row.locator('code').first().getAttribute('title')
    await h.shot(page, 'sources')
    h.item('P01', ['名稱', '類型', '設定', '狀態', '啟用', '操作'].every((k) => head.includes(k)) && /#\d+/.test(txt) && txt.includes('合成') && Boolean(title), `head=${head.replace(/\n/g, '|')} row=${txt.replace(/\n/g, '|')}`)
  })

  const KINDS = {
    folder: { label: '資料夾', fields: ['路徑', '循環讀取', '排序', '檔名樣式'], id: 'P02' },
    file: { label: '單一影像檔', fields: ['路徑'], id: 'P03' },
    usb: { label: 'USB', fields: ['裝置索引', '寬', '高', 'FPS'], id: 'P04' },
    synthetic: { label: '合成', fields: ['寬', '高', '檔名樣式', '隨機種子'], id: 'P05' },
    upload: { label: '手動上傳', fields: [], id: 'P06' },
    plugin: { label: '外掛', fields: ['類別路徑'], id: 'P07' },
  }
  await h.step('P02-P08 新增各種來源', async () => {
    await page.getByRole('button', { name: '新增來源' }).click()
    const dlg = h.dialog(page)
    await dlg.getByRole('button', { name: '儲存' }).click()
    const t0 = await h.toast(page, /請輸入名稱/)
    h.item('P02', Boolean(t0), '名稱空白未提示')
    const select = dlg.locator('select').first()
    let resetOk = true
    for (const [kind, meta] of Object.entries(KINDS)) {
      await select.selectOption(kind)
      await page.waitForTimeout(150)
      const labels = (await dlg.locator('.label, label').allInnerTexts()).join('|')
      const ok = meta.fields.every((f) => labels.includes(f))
      if (kind === 'synthetic') {
        const patternOpts = await dlg.locator('select').nth(1).locator('option').allInnerTexts()
        h.item('P05', patternOpts.join('|').includes('圓點') && patternOpts.join('|').includes('條紋') && patternOpts.join('|').includes('隨機'), `pattern=${patternOpts.join('|')}`)
        const w = await dlg.getByLabel('寬').inputValue()
        if (w !== '640') resetOk = false
      }
      if (kind === 'folder') {
        const sortOpts = await dlg.locator('select').nth(1).locator('option').allInnerTexts()
        h.item('P02', sortOpts.join('|').includes('檔名') && sortOpts.join('|').includes('修改時間'), `sort=${sortOpts.join('|')}`)
      }
      await h.shot(page, `sources-form-${kind}`)
      h.item(meta.id, ok, `${kind} labels=${labels}`)
    }
    h.item('P08', resetOk, '切換類型後 config 未重設為預設')
    // 建立 synthetic
    await select.selectOption('synthetic')
    await dlg.getByLabel('名稱').fill('E2E 合成來源')
    await dlg.getByLabel('寬').fill('320')
    await dlg.getByLabel('高').fill('240')
    await dlg.getByRole('button', { name: '儲存' }).click()
    const t1 = await h.toast(page, /已建立來源/)
    await h.waitGone(page.locator('[role=dialog]'))
    await page.waitForTimeout(500)
    const listed = (await page.locator('tbody').innerText()).includes('E2E 合成來源')
    h.item('P05', Boolean(t1) && listed, `toast=${t1} listed=${listed}`)
    // 建立 upload
    await page.getByRole('button', { name: '新增來源' }).click()
    const d2 = h.dialog(page)
    await d2.locator('select').first().selectOption('upload')
    await d2.getByLabel('名稱').fill('E2E 上傳來源')
    await d2.getByRole('button', { name: '儲存' }).click()
    await h.toast(page, /已建立來源/)
    await h.waitGone(page.locator('[role=dialog]'))
    await page.waitForTimeout(500)
    const upRow = page.locator('tbody tr').filter({ hasText: 'E2E 上傳來源' })
    const hasUpload = (await upRow.locator('label[title=上傳] input[type=file]').count()) === 1
    const png = await h.makePng(page, { w: 200, h: 150, dots: 3 })
    await upRow.locator('input[type=file]').setInputFiles({ name: 'push.png', mimeType: 'image/png', buffer: png })
    const t2 = await h.toast(page, /已儲存/)
    h.item('P06', hasUpload && Boolean(t2), `uploadIcon=${hasUpload} toast=${t2}`)
    // 建立 folder（不存在路徑，預覽會失敗）
    await page.getByRole('button', { name: '新增來源' }).click()
    const d3 = h.dialog(page)
    await d3.locator('select').first().selectOption('folder')
    await d3.getByLabel('名稱').fill('E2E 資料夾來源')
    await d3.getByLabel('路徑').fill('D:/not-exist-e2e')
    await d3.getByRole('button', { name: '儲存' }).click()
    await h.toast(page, /已建立來源/)
    await h.waitGone(page.locator('[role=dialog]'))
  })

  await h.step('P09 預覽', async () => {
    const row = page.locator('tbody tr').filter({ hasText: 'E2E 合成來源' })
    await row.getByRole('button', { name: '預覽' }).click()
    const dlg = h.dialog(page)
    const img = dlg.locator('img')
    await img.waitFor()
    await page.waitForTimeout(1500)
    const loaded = await img.evaluate((el) => el.complete && el.naturalWidth > 0)
    const src1 = await img.getAttribute('src')
    const title = await dlg.locator('h2').innerText()
    await h.shot(page, 'sources-preview')
    await dlg.getByRole('button', { name: '重新整理' }).click()
    await page.waitForTimeout(300)
    const src2 = await img.getAttribute('src')
    await page.keyboard.press('Escape')
    const gone = await h.waitGone(page.locator('[role=dialog]'))
    // 不存在路徑
    const un = h.allowStatus(/4\d\d GET .*\/api\/vision\/sources\/\d+\/preview/)
    await page.locator('tbody tr').filter({ hasText: 'E2E 資料夾來源' }).getByRole('button', { name: '預覽' }).click()
    await page.waitForTimeout(1500)
    const broken = await h.dialog(page).locator('img').evaluate((el) => el.complete && el.naturalWidth === 0)
    await h.shot(page, 'sources-preview-broken')
    await page.keyboard.press('Escape')
    await h.waitGone(page.locator('[role=dialog]'))
    un()
    h.item('P09', loaded && title.includes('E2E 合成來源') && src1 !== src2 && gone && broken, `loaded=${loaded} title=${title} refreshed=${src1 !== src2} esc=${gone} broken=${broken}`)
  })

  await h.step('P10-P11 編輯與啟用', async () => {
    const row = () => page.locator('tbody tr').filter({ hasText: 'E2E 合成來源' })
    await row().getByRole('button', { name: '編輯' }).click()
    const dlg = h.dialog(page)
    const w = await dlg.getByLabel('寬').inputValue()
    const kind = await dlg.locator('select').first().inputValue()
    await dlg.getByLabel('名稱').fill('E2E 合成來源（改）')
    await dlg.getByLabel('寬').fill('400')
    await dlg.getByRole('button', { name: '儲存' }).click()
    const t = await h.toast(page, /已更新來源/)
    await h.waitGone(page.locator('[role=dialog]'))
    await page.waitForTimeout(500)
    const updated = (await page.locator('tbody').innerText()).includes('E2E 合成來源（改）')
    const cfg = await page.locator('tbody tr').filter({ hasText: 'E2E 合成來源（改）' }).locator('code').first().innerText()
    h.item('P10', w === '320' && kind === 'synthetic' && Boolean(t) && updated && cfg.includes('400'), `w=${w} kind=${kind} toast=${t} updated=${updated} cfg=${cfg}`)
    const r = page.locator('tbody tr').filter({ hasText: 'E2E 合成來源（改）' })
    await r.getByRole('switch').click()
    await page.waitForTimeout(800)
    const src = (await h.api.get('/vision/sources')).items.find((s) => s.name === 'E2E 合成來源（改）')
    const off = src && src.is_enabled === false
    await r.getByRole('switch').click()
    await page.waitForTimeout(500)
    h.item('P11', Boolean(off), `is_enabled=${src?.is_enabled}`)
  })

  await h.step('P12 刪除', async () => {
    const r = page.locator('tbody tr').filter({ hasText: 'E2E 資料夾來源' })
    await r.getByRole('button', { name: '刪除' }).click()
    const dlg = h.dialog(page)
    await dlg.locator('text=確定要刪除').waitFor({ timeout: 3000 }).catch(() => null)
    const msg = await dlg.innerText()
    await dlg.getByRole('button', { name: '刪除' }).click()
    const t = await h.toast(page, /已刪除來源/)
    await page.waitForTimeout(600)
    const gone = (await page.locator('tbody tr').filter({ hasText: 'E2E 資料夾來源' }).count()) === 0
    h.item('P12', msg.includes('E2E 資料夾來源') && Boolean(t) && gone, `msg=${msg} toast=${t} gone=${gone}`)
  })

  await h.step('P13 空／錯誤狀態', async () => {
    await page.route('**/api/vision/sources', (route) => route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ items: [] }) }))
    await page.reload()
    await page.waitForLoadState('networkidle')
    await page.waitForTimeout(500)
    const empty = (await page.locator('tbody').innerText()).includes('還沒有影像來源')
    await h.shot(page, 'sources-empty')
    await page.unroute('**/api/vision/sources')
    const un = h.allowStatus(/500 GET .*\/api\/vision\/sources$/)
    await page.route('**/api/vision/sources', (route) => route.fulfill({ status: 500, contentType: 'application/json', body: JSON.stringify({ error: { code: 'boom', message: '來源壞掉' } }) }))
    await page.reload()
    await page.waitForTimeout(2500)
    const err = (await page.locator('main').innerText()).includes('來源壞掉')
    await page.unroute('**/api/vision/sources')
    await page.getByRole('button', { name: '重試' }).click()
    await page.waitForTimeout(800)
    un()
    h.item('P13', empty && err, `empty=${empty} err=${err}`)
  })

  // ============ Q. 資產庫 ============
  await h.step('Q01-Q03 上傳三種資產', async () => {
    await page.goto(`${BASE}/assets`)
    await page.waitForLoadState('networkidle')
    await page.waitForTimeout(500)
    const filter = page.locator('main select').first()
    const opts = await filter.locator('option').allInnerTexts()
    h.item('Q01', opts.join('|').includes('影像') && opts.join('|').includes('模型') && opts.join('|').includes('檔案'), `opts=${opts.join('|')}`)
    await page.getByRole('button', { name: '上傳資產' }).click()
    const dlg = h.dialog(page)
    const uploadBtn = dlg.getByRole('button', { name: '上傳', exact: true })
    const disabled = await uploadBtn.isDisabled()
    const accept = await dlg.locator('input[type=file]').getAttribute('accept')
    const kinds = await dlg.locator('select option').allInnerTexts()
    const png = await h.makePng(page, { w: 120, h: 90, dots: 2 })
    await dlg.locator('input[type=file]').setInputFiles({ name: 'e2e-template.png', mimeType: 'image/png', buffer: png })
    const ph = await dlg.getByLabel('名稱').getAttribute('placeholder')
    h.item('Q02', disabled && accept === 'image/*' && kinds.length === 3 && ph === 'e2e-template.png', `disabled=${disabled} accept=${accept} kinds=${kinds.join('|')} placeholder=${ph}`)
    await dlg.getByLabel('名稱').fill('E2E 影像資產')
    await h.shot(page, 'assets-upload-modal')
    await uploadBtn.click()
    const t1 = await h.toast(page, /已上傳/)
    await h.waitGone(page.locator('[role=dialog]'))
    // model
    await page.getByRole('button', { name: '上傳資產' }).click()
    const d2 = h.dialog(page)
    await d2.locator('select').selectOption('model')
    const acceptModel = await d2.locator('input[type=file]').getAttribute('accept')
    await d2.locator('input[type=file]').setInputFiles({ name: 'e2e-model.onnx', mimeType: 'application/octet-stream', buffer: Buffer.from('not-a-real-model') })
    await d2.getByLabel('名稱').fill('E2E 模型資產')
    await d2.getByRole('button', { name: '上傳', exact: true }).click()
    const t2 = await h.toast(page, /已上傳/)
    await h.waitGone(page.locator('[role=dialog]'))
    // file
    await page.getByRole('button', { name: '上傳資產' }).click()
    const d3 = h.dialog(page)
    await d3.locator('select').selectOption('file')
    await d3.locator('input[type=file]').setInputFiles({ name: 'e2e-notes.txt', mimeType: 'text/plain', buffer: Buffer.from('hello') })
    await d3.getByLabel('名稱').fill('E2E 檔案資產 這個名稱非常長非常長非常長非常長非常長非常長')
    await d3.getByRole('button', { name: '上傳', exact: true }).click()
    const t3 = await h.toast(page, /已上傳/)
    await h.waitGone(page.locator('[role=dialog]'))
    await page.waitForTimeout(800)
    const cards = page.locator('main .card')
    const imgCard = cards.filter({ hasText: 'E2E 影像資產' })
    const imgLoaded = await imgCard.locator('img').evaluate((el) => el.complete && el.naturalWidth > 0).catch(() => false)
    const imgTxt = await imgCard.innerText()
    const modelCard = cards.filter({ hasText: 'E2E 模型資產' })
    const modelIcon = (await modelCard.locator('svg').count()) >= 1
    await h.shot(page, 'assets-grid')
    h.item('Q03', Boolean(t1 && t2 && t3) && imgLoaded && imgTxt.includes('影像') && /120×90/.test(imgTxt) && /B|KB/.test(imgTxt) && modelIcon && (await modelCard.innerText()).includes('模型') && accept === 'image/*' && acceptModel === null, `t=${t1},${t2},${t3} img=${imgLoaded} txt=${imgTxt.replace(/\n/g, '|')} model=${modelIcon} acceptModel=${acceptModel}`)
    const longCard = cards.filter({ hasText: 'E2E 檔案資產' })
    const nameEl = longCard.locator('p.truncate')
    const truncated = await nameEl.evaluate((el) => el.scrollWidth > el.clientWidth && getComputedStyle(el).textOverflow === 'ellipsis')
    const title = await nameEl.getAttribute('title')
    h.item('Q04', truncated && Boolean(title?.includes('非常長')), `truncated=${truncated} title=${title}`)
  })

  await h.step('Q05-Q06 刪除與篩選空狀態', async () => {
    const card = page.locator('main .card').filter({ hasText: 'E2E 檔案資產' })
    await card.getByRole('button', { name: '刪除' }).click()
    const dlg = h.dialog(page)
    const msg = await dlg.innerText()
    await dlg.getByRole('button', { name: '刪除' }).click()
    const t = await h.toast(page, /已刪除/)
    await page.waitForTimeout(600)
    const gone = (await page.locator('main .card').filter({ hasText: 'E2E 檔案資產' }).count()) === 0
    h.item('Q05', msg.includes('E2E 檔案資產') && Boolean(t) && gone, `msg=${msg.slice(0, 60)} toast=${t} gone=${gone}`)
    await page.locator('main select').first().selectOption('file')
    await page.waitForTimeout(800)
    const empty = (await page.locator('main').innerText()).includes('還沒有資產')
    await h.shot(page, 'assets-empty')
    await page.locator('main select').first().selectOption('image')
    await page.waitForTimeout(600)
    const onlyImages = (await page.locator('main .card').filter({ hasText: 'E2E 模型資產' }).count()) === 0 && (await page.locator('main .card').filter({ hasText: 'E2E 影像資產' }).count()) === 1
    await page.locator('main select').first().selectOption('')
    h.item('Q06', empty, '篩選無資料時未顯示空狀態')
    h.item('Q01', onlyImages, '篩選「影像」仍顯示模型')
  })

  // ============ T. 說明頁 ============
  await h.step('T01-T08 說明頁', async () => {
    await page.goto(`${BASE}/help`)
    await page.waitForLoadState('networkidle')
    const tabs = ['quickstart', 'glossary', 'ports', 'tools', 'shortcuts', 'automation', 'accounts']
    let urlOk = true
    for (let i = 0; i < tabs.length; i += 1) {
      await page.locator('[role=tablist] [role=tab]').nth(i).click()
      await page.locator(`[data-testid=help-${tabs[i]}]`).waitFor({ timeout: 5000 })
      await page.waitForTimeout(300)
      if (!page.url().includes(`tab=${tabs[i]}`)) urlOk = false
      const root = page.locator(`[data-testid=help-${tabs[i]}]`).first()
      if (tabs[i] === 'quickstart') h.item('T02', (await root.locator('li.card').count()) === 8, `steps=${await root.locator('li.card').count()}`)
      if (tabs[i] === 'glossary') h.item('T03', (await root.locator('table').count()) === 4, `tables=${await root.locator('table').count()}`)
      if (tabs[i] === 'ports') {
        const rows = await root.locator('tbody tr').count()
        const diamond = await root.locator('tbody tr').last().locator('.rotate-45').count()
        h.item('T04', rows === 11 && diamond === 1, `rows=${rows} diamond=${diamond}`)
      }
      if (tabs[i] === 'tools') {
        await root.locator('.card').first().waitFor({ timeout: 8000 })
        const groups = await root.locator('.card').count()
        const txt = await root.innerText()
        h.item('T05', groups >= 5 && txt.includes('輸入') && txt.includes('輸出') && txt.includes('參數') && txt.includes('blob'), `groups=${groups}`)
      }
      if (tabs[i] === 'shortcuts') h.item('T06', (await root.locator('kbd').count()) >= 10, `kbd=${await root.locator('kbd').count()}`)
      if (tabs[i] === 'accounts') h.item('T08', (await root.locator('li').count()) === 5, `li=${await root.locator('li').count()}`)
      await h.shot(page, `help-${tabs[i]}`)
    }
    h.item('T01', urlOk, 'URL ?tab= 未更新')
    await page.locator('[role=tablist] [role=tab]').nth(5).click()
    await page.getByTestId('help-goto-integration').click()
    await page.waitForURL(/\/integration/, { timeout: 5000 })
    h.item('T07', /\/integration/.test(page.url()), `url=${page.url()}`)
    await page.goto(`${BASE}/help?tab=shortcuts`)
    await page.waitForLoadState('networkidle')
    const deep = (await page.locator('[data-testid=help-shortcuts]').count()) === 1
    h.item('T01', deep, '?tab=shortcuts 深連結未生效')
  })

  // ============ U. 設定頁（金鑰／主題／執行緒池／說明） ============
  await h.step('U01 API 金鑰', async () => {
    await page.goto(`${BASE}/settings`)
    await page.waitForLoadState('networkidle')
    await h.shot(page, 'settings')
    const keyInput = page.locator('input[type=password][autocomplete=off]').first()
    await keyInput.fill('e2e-key-123')
    await page.getByRole('button', { name: '儲存' }).first().click()
    const t = await h.toast(page, /設定已儲存/)
    const stored = await page.evaluate(() => localStorage.getItem('vs.apiKey'))
    await keyInput.fill('')
    await page.getByRole('button', { name: '儲存' }).first().click()
    await page.waitForTimeout(300)
    const cleared = await page.evaluate(() => localStorage.getItem('vs.apiKey'))
    h.item('U01', Boolean(t) && stored === 'e2e-key-123' && cleared === null, `toast=${t} stored=${stored} cleared=${cleared}`)
  })

  await h.step('U02 主題', async () => {
    const res = []
    for (const [label, expectDark, expectStored] of [['深色', true, 'dark'], ['淺色', false, 'light'], ['跟隨系統', false, null]]) {
      await page.getByRole('button', { name: label, exact: true }).click()
      await page.waitForTimeout(200)
      const dark = await page.evaluate(() => document.documentElement.classList.contains('dark'))
      const stored = await page.evaluate(() => localStorage.getItem('vs.theme'))
      const pressed = await page.getByRole('button', { name: label, exact: true }).getAttribute('aria-pressed')
      res.push(`${label}:dark=${dark}/${expectDark} stored=${stored}/${expectStored} pressed=${pressed}`)
      if (label === '深色') await h.shot(page, 'settings-dark')
      if (dark !== expectDark || stored !== expectStored || pressed !== 'true') res.push('MISMATCH')
    }
    h.item('U02', !res.includes('MISMATCH'), res.join(' | '))
  })

  await h.step('U06-U07 執行緒池與接口文字', async () => {
    const txt = await page.locator('main').innerText()
    h.item('U06', txt.includes('max_workers') && txt.includes('active') && txt.includes('images') && /runs/.test(txt), 'capacity card 內容不完整')
    h.item('U07', txt.includes('POST /api/vision/flows/{id}/run') && txt.includes('SSE'), '自動化接口文字缺失')
  })

  // ============ O. 統計頁 ============
  await h.step('O01-O05 統計頁', async () => {
    for (let i = 0; i < 2; i += 1) await h.api.post(`/vision/flows/${demo.id}/run?wait=1`, { context: null, wait: true })
    await page.goto(`${BASE}/flows/${demo.id}/stats`)
    await page.getByTestId('stats-kpi').waitFor({ timeout: 10000 })
    await page.waitForTimeout(1500)
    const header = await page.locator('main h1').innerText()
    const periods = await page.locator('main [role=group] button').allInnerTexts()
    h.item('O01', header.includes(demo.name) && periods.join('|') === '1 小時|8 小時|24 小時|7 天' && (await page.getByRole('button', { name: '回編輯器' }).count()) === 1, `header=${header} periods=${periods.join('|')}`)
    const kpi = await page.getByTestId('stats-kpi').innerText()
    const kpiCards = await page.getByTestId('stats-kpi').locator('.tile-count').count()
    h.item('O02', kpiCards === 6 && ['總執行數', '良率', 'NG 數', '失敗數', '平均耗時', '最大耗時'].every((k) => kpi.includes(k)) && /[1-9]/.test(kpi), `kpi=${kpi.replace(/\n/g, '|')}`)
    const live = await page.locator('main').innerText()
    h.item('O03', live.includes('記憶體即時統計') && live.includes('最近趨勢'), 'live 列缺失')
    const svgs = await page.locator('.recharts-surface').count()
    const bars = await page.locator('.recharts-bar-rectangle').count()
    const line = await page.locator('.recharts-line-curve').count()
    await h.shot(page, 'stats')
    h.item('O04', svgs >= 2 && bars > 0 && line === 1, `svg=${svgs} bars=${bars} line=${line}`)
    await page.getByRole('button', { name: '1 小時' }).click()
    await page.waitForTimeout(800)
    const head = await page.locator('thead').innerText()
    const showing = await page.locator('main').innerText()
    const prevDisabled = await page.getByRole('button', { name: '上一頁' }).isDisabled()
    await page.getByTestId('stats-status-filter').selectOption('cancelled')
    await page.waitForTimeout(800)
    const noData = (await page.locator('tbody').innerText()).includes('此期間沒有執行紀錄')
    await page.getByTestId('stats-status-filter').selectOption('ok')
    await page.locator('tbody tr').filter({ hasText: 'OK' }).first().waitFor({ timeout: 8000 }).catch(() => null)
    await page.waitForTimeout(300)
    const okRows = await page.locator('tbody tr').count()
    await h.shot(page, 'stats-filtered')
    h.item('O05', ['時間', '狀態', '觸發', 'ms', '輸出摘要', '錯誤'].every((k) => head.toLowerCase().includes(k)) && /顯示 \d+–\d+ \/ 共 \d+/.test(showing) && prevDisabled && noData && okRows >= 1, `head=${head.replace(/\n/g, '|')} showing=${/顯示[^\n]*/.exec(showing)?.[0]} prev=${prevDisabled} noData=${noData} okRows=${okRows}`)
    // 無資料圖表：期間 1 小時但用 mock 空
    await page.route('**/api/vision/flows/*/stats?*', (route) => route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ total: 0, by_status: {}, avg_ms: 0, max_ms: 0, hourly: [], live: null }) }))
    await page.route('**/api/vision/flows/*/runs?*', (route) => route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ items: [], total: 0 }) }))
    await page.reload()
    await page.waitForTimeout(1500)
    const empties = await page.locator('main').locator('text=此期間沒有執行紀錄').count()
    await h.shot(page, 'stats-empty')
    await page.unroute('**/api/vision/flows/*/stats?*')
    await page.unroute('**/api/vision/flows/*/runs?*')
    h.item('O04', empties >= 3, `無資料文案出現 ${empties} 次（圖×2＋表）`)
  })

  await h.step('O06 錯誤狀態', async () => {
    const un = h.allowStatus(/500 GET .*\/api\/vision\/flows\/\d+\/stats/)
    await page.route('**/api/vision/flows/*/stats?*', (route) => route.fulfill({ status: 500, contentType: 'application/json', body: JSON.stringify({ error: { code: 'boom', message: '統計壞掉' } }) }))
    await page.reload()
    await page.waitForTimeout(2500)
    const err = (await page.locator('main').innerText()).includes('統計壞掉')
    await page.unroute('**/api/vision/flows/*/stats?*')
    await page.getByRole('button', { name: '重試' }).click()
    await page.waitForTimeout(1200)
    const ok = (await page.getByTestId('stats-kpi').count()) === 1
    un()
    h.item('O06', err && ok, `err=${err} recovered=${ok}`)
  })

  await h.step('O07 統計深色', async () => {
    await page.evaluate(() => localStorage.setItem('vs.theme', 'dark'))
    await page.reload()
    await page.getByTestId('stats-kpi').waitFor({ timeout: 10000 })
    await page.waitForTimeout(1200)
    const tick = await page.locator('.recharts-cartesian-axis-tick-value').first().evaluate((el) => getComputedStyle(el).fill)
    await h.shot(page, 'stats-dark')
    await page.evaluate(() => localStorage.removeItem('vs.theme'))
    h.item('O07', tick && tick !== 'rgb(0, 0, 0)', `tick fill=${tick}`)
  })

  await context.close()
}
