# Generated by Django 5.1.6 on 2026-08-19 13:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('flat', 'Flat rate'), ('tou', 'Time of use')], default='tou', max_length=8)),
                ('currency', models.CharField(default='TWD', max_length=8)),
                ('timezone_name', models.CharField(default='Asia/Taipei', max_length=64)),
                ('demand_charge_per_kw', models.FloatField(default=0.0)),
                ('default_import_price', models.FloatField(default=0.0)),
                ('default_export_price', models.FloatField(default=0.0)),
                ('periods', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='accounts.organization')),
            ],
            options={
                'db_table': 'ems_tariff',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StoragePlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('strategy', models.CharField(choices=[('manual', 'Manual / external control'), ('self_consumption', 'Maximise self-consumption'), ('peak_shaving', 'Peak shaving'), ('tou_arbitrage', 'Time-of-use arbitrage'), ('backup_only', 'Backup reserve only')], default='manual', max_length=20)),
                ('is_enabled', models.BooleanField(default=True)),
                ('contract_capacity_kw', models.FloatField(blank=True, help_text='Contracted demand; the peak-shaving target.', null=True)),
                ('peak_shaving_target_kw', models.FloatField(blank=True, null=True)),
                ('export_limit_kw', models.FloatField(blank=True, help_text='0 disables export entirely.', null=True)),
                ('usable_capacity_kwh', models.FloatField(blank=True, null=True)),
                ('max_charge_kw', models.FloatField(blank=True, null=True)),
                ('max_discharge_kw', models.FloatField(blank=True, null=True)),
                ('min_soc_percent', models.FloatField(default=10.0)),
                ('max_soc_percent', models.FloatField(default=95.0)),
                ('backup_reserve_percent', models.FloatField(default=20.0)),
                ('round_trip_efficiency', models.FloatField(default=0.9)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_plans', to='accounts.organization')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage_plan', to='devices.site')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tariff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans', to='ems.tariff')),
            ],
            options={
                'db_table': 'ems_storage_plan',
            },
        ),
        migrations.CreateModel(
            name='DispatchWindow',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('idle', 'Idle'), ('charge', 'Charge'), ('discharge', 'Discharge'), ('auto', 'Follow strategy')], max_length=12)),
                ('target_power_kw', models.FloatField(blank=True, null=True)),
                ('target_soc_percent', models.FloatField(blank=True, null=True)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField()),
                ('recurrence', models.CharField(blank=True, max_length=200)),
                ('is_enabled', models.BooleanField(default=True)),
                ('priority', models.SmallIntegerField(default=0, help_text='Higher priority wins when windows overlap.')),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_windows', to='accounts.organization')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch_windows', to='devices.site')),
            ],
            options={
                'db_table': 'ems_dispatch_window',
                'ordering': ['starts_at'],
                'indexes': [models.Index(fields=['site', 'starts_at', 'ends_at'], name='ems_dispatc_site_id_53e3c6_idx')],
            },
        ),
        migrations.CreateModel(
            name='EnergyAsset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('grid_meter', 'Grid / point of common coupling meter'), ('load_meter', 'Load meter'), ('pv', 'PV generation'), ('battery', 'Battery storage'), ('ev_charger', 'EV charger'), ('generator', 'Backup generator')], max_length=16)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('power_metric', models.CharField(blank=True, help_text='Instantaneous power, kW after scaling.', max_length=64)),
                ('energy_import_metric', models.CharField(blank=True, help_text='Cumulative imported/charged energy counter.', max_length=64)),
                ('energy_export_metric', models.CharField(blank=True, help_text='Cumulative exported/discharged energy counter.', max_length=64)),
                ('soc_metric', models.CharField(blank=True, help_text='Battery SOC, %.', max_length=64)),
                ('soh_metric', models.CharField(blank=True, help_text='Battery SOH, %.', max_length=64)),
                ('power_scale', models.FloatField(default=1.0)),
                ('energy_scale', models.FloatField(default=1.0)),
                ('invert_sign', models.BooleanField(default=False)),
                ('rated_power_kw', models.FloatField(blank=True, null=True)),
                ('rated_energy_kwh', models.FloatField(blank=True, help_text='Battery usable capacity.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_assets', to='devices.device')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_assets', to='accounts.organization')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_assets', to='devices.site')),
            ],
            options={
                'db_table': 'ems_energy_asset',
                'ordering': ['site', 'role'],
                'indexes': [models.Index(fields=['organization', 'site', 'role'], name='ems_energy__organiz_c99066_idx')],
                'constraints': [models.UniqueConstraint(fields=('site', 'device', 'role'), name='uniq_asset_site_device_role')],
            },
        ),
        migrations.CreateModel(
            name='EnergyInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interval_start', models.DateTimeField(db_index=True)),
                ('interval_seconds', models.PositiveIntegerField(default=900)),
                ('grid_import_kwh', models.FloatField(default=0.0)),
                ('grid_export_kwh', models.FloatField(default=0.0)),
                ('pv_kwh', models.FloatField(default=0.0)),
                ('load_kwh', models.FloatField(default=0.0)),
                ('battery_charge_kwh', models.FloatField(default=0.0)),
                ('battery_discharge_kwh', models.FloatField(default=0.0)),
                ('peak_import_kw', models.FloatField(blank=True, null=True)),
                ('peak_export_kw', models.FloatField(blank=True, null=True)),
                ('avg_load_kw', models.FloatField(blank=True, null=True)),
                ('peak_load_kw', models.FloatField(blank=True, null=True)),
                ('soc_start_percent', models.FloatField(blank=True, null=True)),
                ('soc_end_percent', models.FloatField(blank=True, null=True)),
                ('min_soc_percent', models.FloatField(blank=True, null=True)),
                ('max_soc_percent', models.FloatField(blank=True, null=True)),
                ('tariff_period', models.CharField(blank=True, max_length=40)),
                ('import_price', models.FloatField(blank=True, null=True)),
                ('export_price', models.FloatField(blank=True, null=True)),
                ('energy_cost', models.FloatField(default=0.0)),
                ('export_revenue', models.FloatField(default=0.0)),
                ('estimated_savings', models.FloatField(default=0.0)),
                ('coverage', models.FloatField(default=1.0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_intervals', to='devices.site')),
            ],
            options={
                'db_table': 'ems_energy_interval',
                'ordering': ['-interval_start'],
                'indexes': [models.Index(fields=['site', '-interval_start'], name='idx_interval_site_ts'), models.Index(fields=['organization', '-interval_start'], name='ems_energy__organiz_a26952_idx')],
                'constraints': [models.UniqueConstraint(fields=('site', 'interval_start', 'interval_seconds'), name='uniq_interval_site_start')],
            },
        ),
        migrations.AddConstraint(
            model_name='tariff',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_tariff_org_name'),
        ),
    ]
