# Generated by Django 5.1.6 on 2026-08-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='energyasset',
            name='include_in_balance',
            field=models.BooleanField(default=True, help_text="Off for sub-meters: still charted and still counted per device, but excluded from the site's energy balance."),
        ),
        migrations.AddField(
            model_name='energyinterval',
            name='generator_kwh',
            field=models.FloatField(default=0.0),
        ),
    ]
