# Generated by Django 5.1.6 on 2026-08-21 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_membership_sites'),
        ('devices', '0007_device_last_charge_at_device_last_discharge_at_and_more'),
        ('ems', '0002_balance_and_generator'),
    ]

    operations = [
        migrations.AddField(
            model_name='energyasset',
            name='cost_model',
            field=models.CharField(blank=True, help_text='Registered cost model key; blank uses the role default.', max_length=40),
        ),
        migrations.AddField(
            model_name='energyasset',
            name='cost_parameters',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='energyasset',
            name='session_enter_kw',
            field=models.FloatField(blank=True, help_text='Above this, a session starts. Null = 2% of rating.', null=True),
        ),
        migrations.AddField(
            model_name='energyasset',
            name='session_exit_kw',
            field=models.FloatField(blank=True, help_text='Below this, it ends. Null = half of enter.', null=True),
        ),
        migrations.AddField(
            model_name='energyasset',
            name='session_gap_s',
            field=models.PositiveIntegerField(default=300, help_text='No samples for this long closes the session at the last sample.'),
        ),
        migrations.AddField(
            model_name='energyasset',
            name='session_min_duration_s',
            field=models.PositiveIntegerField(default=60, help_text="Shorter sessions are discarded - a motor's inrush is not a discharge."),
        ),
        migrations.AddField(
            model_name='energyasset',
            name='session_tracking_enabled',
            field=models.BooleanField(default=False, help_text='Detect charge / discharge / running sessions for this asset. Off by default for loads: a circuit that always draws power has one session that never ends, which carries no information.'),
        ),
        migrations.AddField(
            model_name='storageplan',
            name='enforce_limits',
            field=models.BooleanField(default=True, help_text="Refuse dispatch commands that would exceed this plan's power, SOC or export limits."),
        ),
        migrations.AddField(
            model_name='storageplan',
            name='savings_baseline',
            field=models.CharField(choices=[('grid_only', 'Everything bought from the grid'), ('no_storage', 'Same PV, no battery'), ('none', 'Do not compute savings')], default='no_storage', max_length=16),
        ),
        migrations.AlterField(
            model_name='energyinterval',
            name='estimated_savings',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.CreateModel(
            name='DeviceOperatingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('charge', 'Charging'), ('discharge', 'Discharging'), ('running', 'Running')], max_length=12)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_s', models.PositiveIntegerField(blank=True, null=True)),
                ('energy_kwh', models.FloatField(default=0.0)),
                ('peak_kw', models.FloatField(blank=True, null=True)),
                ('avg_kw', models.FloatField(blank=True, null=True)),
                ('start_soc_percent', models.FloatField(blank=True, null=True)),
                ('end_soc_percent', models.FloatField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, choices=[('threshold', 'Power fell below the exit threshold'), ('offline', 'Data stopped arriving'), ('recomputed', 'Still open at the end of the rebuild window')], max_length=12)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operating_sessions', to='ems.energyasset')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_sessions', to='devices.device')),
                ('organization', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'db_table': 'ems_device_session',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['device', 'kind', '-started_at'], name='ems_device__device__343f17_idx'), models.Index(fields=['organization', '-started_at'], name='ems_device__organiz_d4d104_idx')],
                'constraints': [models.UniqueConstraint(fields=('device', 'kind', 'started_at'), name='uniq_session_device_start')],
            },
        ),
        migrations.CreateModel(
            name='EnergyIntervalCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('grid', 'Utility grid'), ('battery', 'Battery storage'), ('generator', 'Backup generator'), ('ev', 'EV charging'), ('other', 'Other')], max_length=12)),
                ('cost_model', models.CharField(blank=True, max_length=40)),
                ('energy_kwh', models.FloatField(default=0.0)),
                ('amount', models.FloatField(default=0.0)),
                ('currency', models.CharField(default='TWD', max_length=8)),
                ('unit_cost', models.FloatField(blank=True, null=True)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('basis', models.CharField(choices=[('measured', 'From measured values'), ('estimated', 'Modelled estimate'), ('unknown', 'Not determinable')], default='estimated', max_length=12)),
                ('interval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='ems.energyinterval')),
            ],
            options={
                'db_table': 'ems_energy_interval_cost',
                'indexes': [models.Index(fields=['source', 'cost_model'], name='ems_energy__source_fe368a_idx')],
                'constraints': [models.UniqueConstraint(fields=('interval', 'source'), name='uniq_interval_cost_source')],
            },
        ),
    ]
