# Generated by Django 5.1.6 on 2026-08-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0003_energyasset_cost_model_energyasset_cost_parameters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageplan',
            name='savings_baseline',
            field=models.CharField(choices=[('grid_only', 'Everything bought from the grid'), ('no_storage', 'Same generation, no battery'), ('none', 'Do not compute savings')], default='no_storage', max_length=16),
        ),
    ]
