# Generated by Django 5.1.6 on 2026-08-21 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0004_savings_baseline_choices'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageplan',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='storage_plans', to='workflows.workflow'),
        ),
        migrations.AlterField(
            model_name='storageplan',
            name='strategy',
            field=models.CharField(choices=[('manual', 'Manual / external control'), ('self_consumption', 'Maximise self-consumption'), ('peak_shaving', 'Peak shaving'), ('tou_arbitrage', 'Time-of-use arbitrage'), ('backup_only', 'Backup reserve only'), ('workflow', 'Run a workflow')], default='manual', max_length=20),
        ),
    ]
