# Generated by Django 5.1.6 on 2026-08-22 00:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organization_reporting_currency'),
        ('devices', '0011_merge_generation_blueprints'),
        ('ems', '0005_storage_plan_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storageplan',
            name='demand_cap_target_kw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storageplan',
            name='max_cycles_per_day',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storageplan',
            name='min_price_spread',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='storageplan',
            name='offpeak_recharge',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storageplan',
            name='temperature_max_c',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storageplan',
            name='temperature_metric',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='storageplan',
            name='strategy',
            field=models.CharField(choices=[('manual', 'Manual / external control'), ('self_consumption', 'Maximise self-consumption'), ('peak_shaving', 'Peak shaving'), ('demand_cap', 'Contract capacity management'), ('tou_arbitrage', 'Time-of-use arbitrage'), ('backup_only', 'Backup reserve only'), ('workflow', 'Run a workflow')], default='manual', max_length=20),
        ),
        migrations.CreateModel(
            name='DemandResponseEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField()),
                ('target_power_kw', models.FloatField()),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('source', models.CharField(default='manual', max_length=12)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dr_events', to='accounts.organization')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dr_events', to='devices.site')),
            ],
            options={
                'db_table': 'ems_dr_event',
                'ordering': ['-starts_at'],
                'indexes': [models.Index(fields=['site', 'starts_at'], name='ems_dr_even_site_id_127672_idx')],
            },
        ),
    ]
