# Generated by Django 5.1.6 on 2026-08-23 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_site_storage_plan'),
        ('ems', '0008_plan_templates_step2'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('made_at', models.DateTimeField(db_index=True)),
                ('horizon_minutes', models.PositiveIntegerField(default=0)),
                ('load_kw', models.FloatField(blank=True, null=True)),
                ('pv_kw', models.FloatField(blank=True, null=True)),
                ('confidence', models.CharField(choices=[('measured', 'Measured'), ('estimated', 'Estimated'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('samples', models.PositiveSmallIntegerField(default=0)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load_forecasts', to='devices.site')),
            ],
            options={
                'db_table': 'ems_load_forecast',
                'ordering': ['starts_at'],
                'indexes': [models.Index(fields=['site', 'starts_at', 'made_at'], name='ems_load_fo_site_id_671d67_idx')],
                'constraints': [models.UniqueConstraint(fields=('site', 'starts_at', 'made_at'), name='uniq_forecast_site_start_made')],
            },
        ),
    ]
