# Generated by Django 5.1.6 on 2026-08-23 04:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organization_reporting_currency'),
        ('devices', '0012_site_storage_plan'),
        ('ems', '0009_load_forecast'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlySettlement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('billing_month', models.DateField()),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('currency', models.CharField(default='TWD', max_length=8)),
                ('tariff_snapshot', models.JSONField(blank=True, default=dict)),
                ('cost_parameters_snapshot', models.JSONField(blank=True, default=dict)),
                ('peak_demand_kw', models.FloatField(blank=True, null=True)),
                ('peak_occurred_at', models.DateTimeField(blank=True, null=True)),
                ('baseline_peak_kw', models.FloatField(blank=True, null=True)),
                ('contract_capacity_kw', models.FloatField(blank=True, null=True)),
                ('energy_charge', models.FloatField(default=0.0)),
                ('demand_charge', models.FloatField(default=0.0)),
                ('excess_penalty', models.FloatField(default=0.0)),
                ('export_revenue', models.FloatField(default=0.0)),
                ('total', models.FloatField(default=0.0)),
                ('baseline_total', models.FloatField(blank=True, null=True)),
                ('savings', models.FloatField(blank=True, null=True)),
                ('basis', models.CharField(choices=[('measured', 'Measured'), ('estimated', 'Estimated'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('interval_count', models.PositiveIntegerField(default=0)),
                ('coverage', models.FloatField(default=0.0)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='devices.site')),
            ],
            options={
                'db_table': 'ems_monthly_settlement',
                'ordering': ['-billing_month'],
                'constraints': [models.UniqueConstraint(fields=('site', 'billing_month'), name='uniq_settlement_site_month')],
            },
        ),
    ]
