# Generated by Django 5.1.6 on 2026-08-23 04:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organization_reporting_currency'),
        ('devices', '0012_site_storage_plan'),
        ('ems', '0011_plan_strategies'),
    ]

    operations = [
        migrations.AddField(
            model_name='energyasset',
            name='voltage_metric',
            field=models.CharField(blank=True, help_text='Grid voltage, V (grid meter only).', max_length=64),
        ),
        migrations.AddField(
            model_name='storageplan',
            name='heartbeat_interval_seconds',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='storageplan',
            name='heartbeat_miss_limit',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='storageplan',
            name='offline_policy',
            field=models.CharField(choices=[('idle', 'Idle (zero power)'), ('hold', 'Hold last setpoint'), ('reserve', 'Charge to backup reserve')], default='reserve', max_length=10),
        ),
        migrations.AddField(
            model_name='storageplan',
            name='on_expiry',
            field=models.CharField(choices=[('idle', 'Idle (zero power)'), ('hold', 'Hold last setpoint'), ('reserve', 'Charge to backup reserve')], default='idle', max_length=10),
        ),
        migrations.AddField(
            model_name='storageplan',
            name='outage_for_seconds',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='storageplan',
            name='outage_voltage_min_v',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storageplan',
            name='setpoint_ttl_seconds',
            field=models.PositiveIntegerField(default=300),
        ),
        migrations.CreateModel(
            name='SiteOutage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('voltage_v', models.FloatField(blank=True, null=True)),
                ('threshold_v', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='devices.device')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outages', to='devices.site')),
            ],
            options={
                'db_table': 'ems_site_outage',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['site', 'started_at', 'ended_at'], name='ems_site_ou_site_id_89895d_idx')],
            },
        ),
    ]
