# Generated by Django 6.1 on 2026-08-28 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('model_file', models.FileField(blank=True, null=True, upload_to='models/')),
                ('scene_key', models.CharField(max_length=50)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='equipment/')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=100)),
                ('domain', models.CharField(choices=[('mechanical', '機構'), ('electrical', '電控'), ('software', '軟體')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('diagram', models.ImageField(blank=True, null=True, upload_to='modules/')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='catalog.equipment')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('equipment', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, help_text='例如：機械手臂部件、輸送帶模組、氣路元件', max_length=50)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('part_number', models.CharField(blank=True, max_length=100)),
                ('function', models.TextField(help_text='元件的功用')),
                ('install_location', models.CharField(help_text='安裝位置（口語描述）', max_length=200)),
                ('specs', models.JSONField(blank=True, default=dict)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='components/')),
                ('photo_credit', models.CharField(blank=True, max_length=200)),
                ('pos_x', models.FloatField(default=0)),
                ('pos_y', models.FloatField(default=0)),
                ('pos_z', models.FloatField(default=0)),
                ('mesh_name', models.CharField(blank=True, max_length=50)),
                ('animation_key', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='catalog.module')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('module', 'slug')},
            },
        ),
    ]
