# Generated by Django 6.1 on 2026-08-28 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='photo_query',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='component',
            name='photo_source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='component',
            name='photo_credit',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
