# Generated by Django 6.1 on 2026-08-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_component_photo_query_component_photo_source_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='utility_guide',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='module',
            name='domain',
            field=models.CharField(choices=[('mechanical', '機構'), ('electrical', '電控'), ('software', '軟體'), ('utility', '水氣電')], max_length=20),
        ),
    ]
