# Generated by Django 6.1 on 2026-08-28 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_equipment_utility_guide_alter_module_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='model_file',
            field=models.FileField(blank=True, null=True, upload_to='models/components/'),
        ),
        migrations.AddField(
            model_name='component',
            name='model_prompt',
            field=models.CharField(blank=True, help_text='text-to-CAD 的英文提示詞', max_length=300),
        ),
    ]
