# Generated by Django 5.1.6 on 2026-08-19 13:31

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mqtt_username', models.CharField(db_index=True, max_length=128, unique=True)),
                ('hashed_password', models.CharField(max_length=256)),
                ('allowed_client_id', models.CharField(blank=True, max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('last_auth_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'devices_credential',
            },
        ),
        migrations.CreateModel(
            name='DeviceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_index=True)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('notice', 'Notice'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=16)),
                ('code', models.CharField(blank=True, db_index=True, max_length=64)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'devices_event',
                'ordering': ['-ts'],
            },
        ),
        migrations.CreateModel(
            name='DeviceStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('unknown', 'Unknown')], max_length=16)),
                ('previous_status', models.CharField(blank=True, max_length=16)),
                ('reason', models.CharField(blank=True, help_text='lwt | report | timeout', max_length=64)),
                ('ts', models.DateTimeField(db_index=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'devices_status_event',
                'ordering': ['-ts'],
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=80)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('battery', 'Battery / BESS'), ('pcs', 'Power conversion system'), ('pv_inverter', 'PV inverter'), ('meter', 'Energy meter'), ('ev_charger', 'EV charger'), ('controller', 'EMS controller'), ('sensor', 'Sensor'), ('gateway', 'Gateway'), ('other', 'Other')], default='other', max_length=20)),
                ('manufacturer', models.CharField(blank=True, max_length=120)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=64)),
                ('command_definitions', models.JSONField(blank=True, default=list)),
                ('default_metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'devices_device_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.SlugField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=400)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2', max_length=2)),
                ('postal_code', models.CharField(blank=True, max_length=32)),
                ('latitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('timezone_name', models.CharField(default='UTC', max_length=64)),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'devices_site',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Command',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=80)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('accepted', 'Accepted by device'), ('succeeded', 'Succeeded'), ('rejected', 'Rejected by device'), ('failed', 'Failed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('issued_by_label', models.CharField(blank=True, max_length=200)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('acked_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('idempotency_key', models.CharField(blank=True, max_length=80)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commands', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='accounts.organization')),
            ],
            options={
                'db_table': 'devices_command',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('device_id', models.CharField(db_index=True, max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message="Device ID must be 3-64 characters of letters, digits, '.', '_' or '-' and must not contain MQTT wildcards.", regex='^[A-Za-z0-9][A-Za-z0-9_.-]{2,63}$')])),
                ('name', models.CharField(max_length=200)),
                ('serial_number', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('firmware_version', models.CharField(blank=True, max_length=64)),
                ('hardware_version', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_telemetry_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('rssi', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('address', models.CharField(blank=True, max_length=400)),
                ('location_source', models.CharField(blank=True, help_text='device | manual | site', max_length=16)),
                ('location_updated_at', models.DateTimeField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_enabled', models.BooleanField(default=True, help_text='Disabled devices are ignored by the ingest pipeline.')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='accounts.organization')),
            ],
            options={
                'db_table': 'devices_device',
                'ordering': ['name'],
            },
        ),
    ]
