# Generated by Django 5.1.6 on 2026-08-19 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('devices', '0001_initial'),
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='recording_policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='telemetry.recordingpolicy'),
        ),
        migrations.AddField(
            model_name='command',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='devices.device'),
        ),
        migrations.AddField(
            model_name='devicecredential',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='devices.device'),
        ),
        migrations.AddField(
            model_name='deviceevent',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='devices.device'),
        ),
        migrations.AddField(
            model_name='deviceevent',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_events', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='devicestatusevent',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='devices.device'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Null means a built-in blueprint shared by all tenants.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_types', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='device',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='devices.devicetype'),
        ),
        migrations.AddField(
            model_name='site',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='device',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='devices.site'),
        ),
        migrations.AddIndex(
            model_name='command',
            index=models.Index(fields=['organization', '-created_at'], name='devices_com_organiz_918e92_idx'),
        ),
        migrations.AddIndex(
            model_name='command',
            index=models.Index(fields=['device', '-created_at'], name='devices_com_device__03abd0_idx'),
        ),
        migrations.AddIndex(
            model_name='command',
            index=models.Index(fields=['status', 'expires_at'], name='devices_com_status_59cf9d_idx'),
        ),
        migrations.AddConstraint(
            model_name='command',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('organization', 'idempotency_key'), name='uniq_command_idempotency'),
        ),
        migrations.AddIndex(
            model_name='deviceevent',
            index=models.Index(fields=['organization', '-ts'], name='devices_eve_organiz_812303_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceevent',
            index=models.Index(fields=['device', '-ts'], name='devices_eve_device__4e04af_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceevent',
            index=models.Index(fields=['device', 'level', '-ts'], name='devices_eve_device__1db2ff_idx'),
        ),
        migrations.AddIndex(
            model_name='devicestatusevent',
            index=models.Index(fields=['device', '-ts'], name='devices_sta_device__0f7224_idx'),
        ),
        migrations.AddConstraint(
            model_name='devicetype',
            constraint=models.UniqueConstraint(fields=('organization', 'key'), name='uniq_device_type_org_key'),
        ),
        migrations.AddConstraint(
            model_name='devicetype',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('key',), name='uniq_device_type_global_key'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['organization', 'is_active'], name='devices_sit_organiz_8b769c_idx'),
        ),
        migrations.AddConstraint(
            model_name='site',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_site_org_code'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['organization', 'status'], name='devices_dev_organiz_c0273e_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['organization', 'site'], name='devices_dev_organiz_571a22_idx'),
        ),
    ]
