# Generated by Django 5.1.6 on 2026-08-20 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('devices', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='kind',
            field=models.CharField(choices=[('site', 'Site / plant'), ('area', 'Area / workshop'), ('line', 'Production line'), ('group', 'Logical group')], default='site', max_length=16),
        ),
        migrations.AddField(
            model_name='site',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='devices.site'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['organization', 'parent'], name='devices_sit_organiz_7869e5_idx'),
        ),
    ]
