# Generated by Django 5.1.6 on 2026-08-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_site_hierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='can_charge',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='can_discharge',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='can_export',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='capability_source',
            field=models.CharField(choices=[('blueprint', 'Inherited from the blueprint'), ('manual', 'Set by an operator'), ('device', "Accepted from the device's declaration")], default='blueprint', max_length=16),
        ),
        migrations.AddField(
            model_name='device',
            name='commissioning_state',
            field=models.CharField(choices=[('pending', 'Pending confirmation'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='confirmed', max_length=16),
        ),
        migrations.AddField(
            model_name='device',
            name='is_dispatchable',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='can_charge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='can_discharge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='can_export',
            field=models.BooleanField(default=False, help_text='May push power back towards the grid.'),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='is_dispatchable',
            field=models.BooleanField(default=True, help_text='Accepts control commands at all. False for meters.'),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='category',
            field=models.CharField(choices=[('battery', 'Battery / BESS'), ('pcs', 'Power conversion system'), ('pv_inverter', 'PV inverter'), ('meter', 'Energy meter'), ('load', 'Electrical load'), ('generator', 'Backup generator'), ('ev_charger', 'EV charger'), ('controller', 'EMS controller'), ('sensor', 'Sensor'), ('gateway', 'Gateway'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
