# Generated by Django 5.1.6 on 2026-08-20 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_device_capabilities'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('schema_version', models.PositiveSmallIntegerField(default=0)),
                ('received_at', models.DateTimeField()),
                ('state', models.CharField(choices=[('pending', 'Awaiting review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('superseded', 'Superseded by a newer declaration')], default='pending', max_length=16)),
                ('diff_summary', models.JSONField(blank=True, default=dict)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='declaration', to='devices.device')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'devices_declaration',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['state', '-received_at'], name='devices_dec_state_ed0172_idx')],
            },
        ),
    ]
