# Generated by Django 5.1.6 on 2026-08-20 10:51

import django.db.models.deletion
from django.db import migrations, models


def forwards_lifecycle(apps, schema_editor):
    """Map the old two-value commissioning field onto the lifecycle states.

    ``confirmed`` becomes ``active``; ``pending`` and ``rejected`` keep their
    meaning. Declarations lose their approval states: under the new policy a
    declaration describes agreement, not a pending change request, so anything
    that was awaiting review becomes ``matched`` or ``mismatched`` depending on
    whether it actually differed.
    """
    Device = apps.get_model("devices", "Device")
    Device.objects.filter(commissioning_state="confirmed").update(
        commissioning_state="active"
    )
    # A device someone had disabled by hand keeps that intent, expressed as a
    # lifecycle state so the two fields cannot disagree from here on.
    Device.objects.filter(is_enabled=False, commissioning_state="active").update(
        commissioning_state="suspended"
    )

    Declaration = apps.get_model("devices", "DeviceDeclaration")
    for record in Declaration.objects.all().iterator():
        record.state = "mismatched" if record.diff_summary else "matched"
        record.identity_mismatch = "category" in (record.diff_summary or {})
        record.save(update_fields=["state", "identity_mismatch"])


def backwards_lifecycle(apps, schema_editor):
    Device = apps.get_model("devices", "Device")
    Device.objects.filter(
        commissioning_state__in=["active", "suspended", "retired"]
    ).update(commissioning_state="confirmed")


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_device_declaration'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='replaced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='devices.device'),
        ),
        migrations.AddField(
            model_name='device',
            name='retired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicedeclaration',
            name='identity_mismatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='device',
            name='commissioning_state',
            field=models.CharField(choices=[('pending', 'Pending commissioning'), ('active', 'Active'), ('suspended', 'Suspended'), ('retired', 'Retired'), ('rejected', 'Rejected')], db_index=True, default='active', max_length=16),
        ),
        migrations.AlterField(
            model_name='devicedeclaration',
            name='state',
            field=models.CharField(choices=[('matched', 'Matches the register'), ('mismatched', 'Differs from the register'), ('acknowledged', 'Difference acknowledged')], default='matched', max_length=16),
        ),
        migrations.RunPython(forwards_lifecycle, backwards_lifecycle),
    ]
