# Generated by Django 5.1.6 on 2026-08-21 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_device_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_charge_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='last_discharge_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='last_running_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
