# Generated by Django 5.1.6 on 2026-08-21 03:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userpreference'),
        ('devices', '0007_device_last_charge_at_device_last_discharge_at_and_more'),
        ('telemetry', '0002_metric_counter_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='annual_maintenance_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='capital_cost',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='commissioned_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='cost_currency',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name='device',
            name='expected_life_years',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='devicetype',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('serial_number', ''), _negated=True), ('deleted_at__isnull', True)), fields=('organization', 'serial_number'), name='uniq_device_org_serial'),
        ),
    ]
