# Generated by Django 5.1.6 on 2026-08-26 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organization_reporting_currency'),
        ('devices', '0012_site_storage_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngressDebug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled_until', models.DateTimeField(blank=True, null=True)),
                ('node_filter', models.CharField(blank=True, max_length=80)),
                ('capture_payload', models.BooleanField(default=True)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ingress_debug', to='accounts.organization')),
            ],
            options={
                'db_table': 'ingress_debug',
            },
        ),
        migrations.CreateModel(
            name='IngressTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_index=True)),
                ('stage', models.CharField(max_length=12)),
                ('outcome', models.CharField(max_length=12)),
                ('group_id', models.CharField(blank=True, max_length=80)),
                ('edge_node_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('device_id', models.CharField(blank=True, max_length=80)),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('kind', models.CharField(blank=True, max_length=16)),
                ('reason', models.CharField(blank=True, max_length=64)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('size', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'db_table': 'ingress_trace',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['organization', 'ts'], name='ingress_tra_organiz_c0f99f_idx')],
            },
        ),
    ]
