# Generated by Django 6.1 on 2026-08-30 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_component_model_file_component_model_prompt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('order', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['level', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('hardware', '硬體與通訊'), ('vision', '視覺與 AI'), ('motion', '運動控制'), ('software', '軟體與系統'), ('troubleshooting', '除錯與 Log 分析')], max_length=20)),
                ('tags', models.JSONField(blank=True, default=list, help_text='如 ["LabVIEW", "EtherCAT"]')),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('content_markdown', models.TextField(blank=True)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='如 MEC-01', max_length=20, unique=True)),
                ('category', models.CharField(choices=[('mech', '機構'), ('pne', '氣路'), ('elec', '電控'), ('soft', '軟體'), ('cnv', '輸送帶模組'), ('arm', '機械手臂'), ('aoi', 'AOI 光學'), ('fcs', '氫燃料電池')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=150)),
                ('function', models.TextField(help_text='這個元件在做什麼')),
                ('install_location', models.CharField(help_text='裝在哪裡', max_length=300)),
                ('tip', models.TextField(blank=True, help_text='現場重點／最常見的錯誤')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='knowledge/')),
                ('photo_credit', models.CharField(blank=True, max_length=300)),
                ('photo_source_url', models.URLField(blank=True)),
                ('photo_query', models.CharField(blank=True, help_text='抓圖用英文關鍵字', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('components', models.ManyToManyField(blank=True, related_name='knowledge_cards', to='catalog.component')),
            ],
            options={
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='IdentificationGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('look', models.CharField(help_text='外觀描述（學員從這裡找起）', max_length=300)),
                ('tell', models.TextField(help_text='怎麼確定是哪一種')),
                ('key_fields', models.TextField(help_text='一定要核對的欄位')),
                ('common_mistake', models.TextField(help_text='最常見的收錯')),
                ('order', models.PositiveIntegerField(default=0)),
                ('candidates', models.ManyToManyField(blank=True, related_name='identification_guides', to='training.knowledgecard')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('content_markdown', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('card_category', models.CharField(blank=True, max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('cards', models.ManyToManyField(blank=True, related_name='lessons', to='training.knowledgecard')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='training.course')),
                ('equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='catalog.equipment')),
            ],
            options={
                'ordering': ['order', 'id'],
                'unique_together': {('course', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', '學員'), ('mentor', '導師'), ('admin', '管理員')], default='student', max_length=20)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, help_text='部門／課別', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('spec_markdown', models.TextField(blank=True, help_text='需求規格與輸入輸出定義')),
                ('acceptance_markdown', models.TextField(blank=True, help_text='驗收標準')),
                ('published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='training.course')),
            ],
            options={
                'ordering': ['level', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_url', models.URLField(blank=True)),
                ('upload', models.FileField(blank=True, null=True, upload_to='submissions/')),
                ('note', models.TextField(blank=True, help_text='學員自述：做法與已知問題')),
                ('status', models.CharField(choices=[('submitted', '已提交'), ('under_review', '審核中'), ('passed', '通過'), ('rejected', '退回')], default='submitted', max_length=20)),
                ('mentor_feedback', models.TextField(blank=True)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='training.project')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('options', models.JSONField(default=list, help_text='選項字串陣列')),
                ('answer_index', models.PositiveSmallIntegerField(help_text='正解在 options 中的索引，從 0 起算')),
                ('explanation', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='training.course')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_index', models.PositiveSmallIntegerField()),
                ('correct', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='training.quizquestion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='training.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
