# Generated by Django 5.1.6 on 2026-08-21 14:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_organization_reporting_currency'),
        ('devices', '0011_merge_generation_blueprints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('graph', models.JSONField(blank=True, default=dict)),
                ('is_enabled', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='accounts.organization')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows', to='devices.site')),
            ],
            options={
                'db_table': 'workflows_workflow',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('graph', models.JSONField(blank=True, default=dict)),
                ('workflow_version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Queued'), ('running', 'Running'), ('waiting', 'Waiting on a timer'), ('succeeded', 'Finished'), ('failed', 'Failed'), ('cancelled', 'Stopped by an operator')], default='pending', max_length=12)),
                ('trigger', models.CharField(choices=[('manual', 'Started from the editor'), ('api', 'Started over the API'), ('workflow', 'Started by another workflow'), ('storage_plan', 'Started by a storage plan')], default='manual', max_length=16)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('dry_run', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('wake_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('steps_taken', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_runs', to='accounts.organization')),
                ('parent_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='workflows.workflowrun')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='workflows.workflow')),
            ],
            options={
                'db_table': 'workflows_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('node_id', models.CharField(blank=True, max_length=64)),
                ('node_label', models.CharField(blank=True, max_length=200)),
                ('level', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=8)),
                ('message', models.TextField(blank=True)),
                ('branch', models.CharField(blank=True, max_length=32)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='workflows.workflowrun')),
            ],
            options={
                'db_table': 'workflows_log',
                'ordering': ['ts', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message="Node id must be 1-64 characters of letters, digits, '_' or '-'.", regex='^[A-Za-z0-9][A-Za-z0-9_-]{0,63}$')])),
                ('state', models.JSONField(blank=True, default=dict)),
                ('wake_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='workflows.workflowrun')),
            ],
            options={
                'db_table': 'workflows_token',
            },
        ),
        migrations.AddConstraint(
            model_name='workflow',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('organization', 'name'), name='uniq_workflow_org_name'),
        ),
        migrations.AddIndex(
            model_name='workflowrun',
            index=models.Index(fields=['organization', 'status'], name='workflows_r_organiz_c8053d_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowrun',
            index=models.Index(fields=['status', 'wake_at'], name='workflows_r_status_c2736b_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowlog',
            index=models.Index(fields=['run', 'ts'], name='workflows_l_run_id_0bf214_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowtoken',
            index=models.Index(fields=['run', 'node_id'], name='workflows_t_run_id_4293be_idx'),
        ),
    ]
