# Generated by Django 5.1.6 on 2026-08-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflowrun',
            name='step_delay_seconds',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='workflowrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Queued'), ('running', 'Running'), ('waiting', 'Waiting on a timer'), ('paused', 'Paused'), ('succeeded', 'Finished'), ('failed', 'Failed'), ('cancelled', 'Stopped by an operator')], default='pending', max_length=12),
        ),
    ]
