# Generated by Django 5.1.6 on 2026-08-19 13:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('triggered', 'Triggered'), ('retriggered', 'Re-triggered'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('auto_resolved', 'Automatically resolved'), ('notified', 'Notification sent'), ('note', 'Note added')], max_length=16)),
                ('actor_label', models.CharField(blank=True, max_length=200)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('value', models.FloatField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'alerts_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('is_enabled', models.BooleanField(default=True)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('major', 'Major'), ('critical', 'Critical')], default='warning', max_length=12)),
                ('scope', models.CharField(choices=[('organization', 'All devices'), ('site', 'Devices at a site'), ('device_type', 'Devices of a blueprint'), ('device', 'Selected devices')], default='organization', max_length=16)),
                ('metric_key', models.CharField(blank=True, max_length=64)),
                ('operator', models.CharField(choices=[('gt', 'Greater than'), ('gte', 'Greater than or equal'), ('lt', 'Less than'), ('lte', 'Less than or equal'), ('eq', 'Equal to'), ('neq', 'Not equal to'), ('outside', 'Outside range'), ('inside', 'Inside range'), ('no_data', 'No data received'), ('offline', 'Device offline')], default='gt', max_length=12)),
                ('threshold', models.FloatField(blank=True, null=True)),
                ('threshold_upper', models.FloatField(blank=True, null=True)),
                ('hysteresis', models.FloatField(default=0.0)),
                ('for_duration_seconds', models.PositiveIntegerField(default=0)),
                ('cooldown_seconds', models.PositiveIntegerField(default=300)),
                ('auto_resolve', models.BooleanField(default=True)),
                ('message_template', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'db_table': 'alerts_rule',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('channel_type', models.CharField(choices=[('webhook', 'HTTP webhook'), ('email', 'Email'), ('mqtt', 'MQTT publish')], max_length=12)),
                ('is_enabled', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('min_severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('major', 'Major'), ('critical', 'Critical')], default='warning', max_length=12)),
            ],
            options={
                'db_table': 'alerts_notification_channel',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=12)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=500)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alerts_notification_delivery',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('rule', 'Server rule engine'), ('device', 'Reported by device'), ('system', 'Platform')], default='rule', max_length=12)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('major', 'Major'), ('critical', 'Critical')], default='warning', max_length=12)),
                ('status', models.CharField(choices=[('firing', 'Firing'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='firing', max_length=16)),
                ('metric_key', models.CharField(blank=True, max_length=64)),
                ('code', models.CharField(blank=True, db_index=True, max_length=64)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True)),
                ('trigger_value', models.FloatField(blank=True, null=True)),
                ('threshold', models.FloatField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('fingerprint', models.CharField(db_index=True, max_length=64)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('last_triggered_at', models.DateTimeField()),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledge_note', models.CharField(blank=True, max_length=500)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolve_note', models.CharField(blank=True, max_length=500)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alerts_alert',
                'ordering': ['-started_at'],
            },
        ),
    ]
