# Generated by Django 5.1.6 on 2026-08-19 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('alerts', '0001_initial'),
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='devices.device'),
        ),
        migrations.AddField(
            model_name='alert',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='alert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alertevent',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='alerts.alert'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='devices.devicetype'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='devices',
            field=models.ManyToManyField(blank=True, related_name='alert_rules', to='devices.device'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='devices.site'),
        ),
        migrations.AddField(
            model_name='alert',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='alerts.alertrule'),
        ),
        migrations.AddField(
            model_name='notificationchannel',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_channels', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='channels',
            field=models.ManyToManyField(blank=True, related_name='rules', to='alerts.notificationchannel'),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='alerts.alert'),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='alerts.notificationchannel'),
        ),
        migrations.AddIndex(
            model_name='alertevent',
            index=models.Index(fields=['alert', '-created_at'], name='alerts_even_alert_i_37b5ad_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['organization', 'status', '-started_at'], name='alerts_aler_organiz_83b6ab_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['device', '-started_at'], name='alerts_aler_device__5a7030_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['organization', 'severity', 'status'], name='alerts_aler_organiz_633ca2_idx'),
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'resolved'), _negated=True), fields=('fingerprint',), name='uniq_open_alert_fingerprint'),
        ),
        migrations.AddConstraint(
            model_name='notificationchannel',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_channel_org_name'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['organization', 'is_enabled'], name='alerts_rule_organiz_ab544a_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['metric_key', 'is_enabled'], name='alerts_rule_metric__8c7728_idx'),
        ),
        migrations.AddConstraint(
            model_name='alertrule',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_rule_org_name'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['alert', 'channel'], name='alerts_noti_alert_i_ad35a5_idx'),
        ),
    ]
