# Generated by Django 5.1.6 on 2026-08-21 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_initial'),
        ('devices', '0011_merge_generation_blueprints'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationchannel',
            name='min_event_level',
            field=models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('notice', 'Notice'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='error', max_length=16),
        ),
        migrations.AddField(
            model_name='notificationchannel',
            name='notify_alerts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationchannel',
            name='notify_events',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationdelivery',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='devices.deviceevent'),
        ),
        migrations.AlterField(
            model_name='notificationchannel',
            name='channel_type',
            field=models.CharField(choices=[('webhook', 'HTTP webhook'), ('email', 'Email'), ('line', 'LINE bot'), ('mqtt', 'MQTT publish')], max_length=12),
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='alert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='alerts.alert'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['event', 'channel'], name='alerts_noti_event_i_6bf06e_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationdelivery',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('alert__isnull', False), ('event__isnull', True)), models.Q(('alert__isnull', True), ('event__isnull', False)), _connector='OR'), name='delivery_alert_xor_event'),
        ),
    ]
