# Generated by Django 5.1.6 on 2026-08-19 13:31

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordingPolicy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('record_unlisted_metrics', models.BooleanField(default=True)),
                ('default_retention_days', models.PositiveIntegerField(default=365)),
                ('default_min_interval_seconds', models.PositiveIntegerField(default=0)),
                ('default_max_interval_seconds', models.PositiveIntegerField(default=3600)),
                ('device_type', models.ForeignKey(blank=True, help_text='Applied automatically to devices of this blueprint.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recording_policies', to='devices.devicetype')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recording_policies', to='accounts.organization')),
            ],
            options={
                'db_table': 'telemetry_recording_policy',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecordingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_key', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Metric keys are lowercase snake_case, max 64 characters.', regex='^[a-z][a-z0-9_]{0,63}$')])),
                ('enabled', models.BooleanField(default=True)),
                ('min_interval_seconds', models.PositiveIntegerField(default=0)),
                ('max_interval_seconds', models.PositiveIntegerField(default=3600)),
                ('deadband_absolute', models.FloatField(blank=True, null=True)),
                ('deadband_percent', models.FloatField(blank=True, null=True)),
                ('retention_days', models.PositiveIntegerField(blank=True, null=True)),
                ('keep_rollups', models.BooleanField(default=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='telemetry.recordingpolicy')),
            ],
            options={
                'db_table': 'telemetry_recording_rule',
                'ordering': ['metric_key'],
            },
        ),
        migrations.CreateModel(
            name='Rollup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_key', models.CharField(max_length=64)),
                ('interval_seconds', models.PositiveIntegerField()),
                ('bucket_start', models.DateTimeField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('avg_value', models.FloatField(blank=True, null=True)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('sum_value', models.FloatField(blank=True, null=True)),
                ('first_value', models.FloatField(blank=True, null=True)),
                ('last_value', models.FloatField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rollups', to='devices.device')),
                ('organization', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'db_table': 'telemetry_rollup',
            },
        ),
        migrations.CreateModel(
            name='TelemetrySample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_key', models.CharField(max_length=64)),
                ('ts', models.DateTimeField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('quality', models.SmallIntegerField(choices=[(0, 'Good'), (1, 'Out of plausible range'), (2, 'Substituted / interpolated'), (3, 'Bad')], default=0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='devices.device')),
                ('organization', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'db_table': 'telemetry_sample',
            },
        ),
        migrations.CreateModel(
            name='LatestSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_key', models.CharField(max_length=64)),
                ('ts', models.DateTimeField()),
                ('value', models.FloatField(blank=True, null=True)),
                ('value_text', models.TextField(blank=True, null=True)),
                ('quality', models.SmallIntegerField(choices=[(0, 'Good'), (1, 'Out of plausible range'), (2, 'Substituted / interpolated'), (3, 'Bad')], default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latest_samples', to='devices.device')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.organization')),
            ],
            options={
                'db_table': 'telemetry_latest_sample',
                'indexes': [models.Index(fields=['organization', 'metric_key'], name='telemetry_l_organiz_d91ee0_idx')],
                'constraints': [models.UniqueConstraint(fields=('device', 'metric_key'), name='uniq_latest_device_metric')],
            },
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(message='Metric keys are lowercase snake_case, max 64 characters.', regex='^[a-z][a-z0-9_]{0,63}$')])),
                ('display_name', models.CharField(max_length=120)),
                ('translations', models.JSONField(blank=True, default=dict)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(blank=True, help_text='W, kWh, V, A, degC, %', max_length=24)),
                ('value_type', models.CharField(choices=[('float', 'Float'), ('integer', 'Integer'), ('boolean', 'Boolean'), ('string', 'String'), ('json', 'JSON')], default='float', max_length=12)),
                ('kind', models.CharField(choices=[('gauge', 'Gauge'), ('counter', 'Cumulative counter'), ('state', 'State / enum')], default='gauge', max_length=12)),
                ('aggregation', models.CharField(choices=[('avg', 'Average'), ('sum', 'Sum'), ('min', 'Minimum'), ('max', 'Maximum'), ('last', 'Last value'), ('counter', 'Counter delta')], default='avg', max_length=12)),
                ('decimals', models.PositiveSmallIntegerField(default=2)),
                ('min_value', models.FloatField(blank=True, null=True)),
                ('max_value', models.FloatField(blank=True, null=True)),
                ('state_map', models.JSONField(blank=True, default=dict)),
                ('category', models.CharField(blank=True, help_text='power, energy, ...', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(blank=True, help_text='Null means a built-in metric available to every tenant.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='accounts.organization')),
            ],
            options={
                'db_table': 'telemetry_metric',
                'ordering': ['key'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'key'), name='uniq_metric_org_key'), models.UniqueConstraint(condition=models.Q(('organization__isnull', True)), fields=('key',), name='uniq_metric_global_key')],
            },
        ),
        migrations.AddConstraint(
            model_name='recordingpolicy',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_policy_org_name'),
        ),
        migrations.AddConstraint(
            model_name='recordingpolicy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('organization',), name='uniq_policy_org_default'),
        ),
        migrations.AddConstraint(
            model_name='recordingrule',
            constraint=models.UniqueConstraint(fields=('policy', 'metric_key'), name='uniq_rule_policy_metric'),
        ),
        migrations.AddIndex(
            model_name='rollup',
            index=models.Index(fields=['device', 'metric_key', 'interval_seconds', '-bucket_start'], name='idx_rollup_lookup'),
        ),
        migrations.AddConstraint(
            model_name='rollup',
            constraint=models.UniqueConstraint(fields=('device', 'metric_key', 'interval_seconds', 'bucket_start'), name='uniq_rollup_bucket'),
        ),
        migrations.AddIndex(
            model_name='telemetrysample',
            index=models.Index(fields=['device', 'metric_key', '-ts'], name='idx_sample_dev_metric_ts'),
        ),
        migrations.AddIndex(
            model_name='telemetrysample',
            index=models.Index(fields=['organization', '-ts'], name='idx_sample_org_ts'),
        ),
        migrations.AddConstraint(
            model_name='telemetrysample',
            constraint=models.UniqueConstraint(fields=('device', 'metric_key', 'ts'), name='uniq_sample_device_metric_ts'),
        ),
    ]
