# Generated by Django 5.1.6 on 2026-08-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='counter_max',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
