# Generated by Django 5.1.6 on 2026-09-04 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_kind', models.CharField(default='user', max_length=16)),
                ('actor_name', models.CharField(blank=True, default='', max_length=150)),
                ('action', models.CharField(db_index=True, max_length=40)),
                ('target_type', models.CharField(blank=True, default='', max_length=24)),
                ('target_id', models.CharField(blank=True, default='', max_length=64)),
                ('target_name', models.CharField(blank=True, default='', max_length=160)),
                ('summary', models.CharField(blank=True, default='', max_length=400)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-at', '-id'],
                'indexes': [models.Index(fields=['target_type', 'target_id', '-at'], name='core_auditl_target__b3ba5a_idx'), models.Index(fields=['actor', '-at'], name='core_auditl_actor_i_b5d7d1_idx')],
            },
        ),
    ]
