# Generated by Django 6.1 on 2026-08-28 06:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mode', models.CharField(choices=[('ai', 'AI 產碼'), ('code', '直接執行程式')], default='ai', max_length=10)),
                ('prompt', models.TextField(blank=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('code', models.TextField(blank=True, help_text='build123d 產生器程式（定義 gen_step()）')),
                ('status', models.CharField(choices=[('queued', '排隊中'), ('generating', 'AI 產生程式中'), ('building', '建置 CAD 中'), ('done', '完成'), ('failed', '失敗')], default='queued', max_length=12)),
                ('log', models.TextField(blank=True)),
                ('error', models.TextField(blank=True)),
                ('ai_notes', models.TextField(blank=True, help_text='AI 的說明與假設')),
                ('glb', models.CharField(blank=True, max_length=300)),
                ('step', models.CharField(blank=True, max_length=300)),
                ('stl', models.CharField(blank=True, max_length=300)),
                ('three_mf', models.CharField(blank=True, max_length=300)),
                ('snapshot', models.CharField(blank=True, max_length=300)),
                ('facts', models.JSONField(blank=True, default=dict)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='cadstudio.cadjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
