# Generated by Django 5.1.6 on 2026-09-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userpref'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpref',
            name='agent',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
