# Generated by Django 5.1.6 on 2026-09-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userpref_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpref',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('engineer', 'engineer'), ('operator', 'operator')], default='engineer', max_length=16),
        ),
    ]
